-- ========================================
-- MIGRACIÓN 000350: Drop v4_ssot functions (full) (DOWN)
-- ========================================

BEGIN;
DROP FUNCTION IF EXISTS v4_ssot.stock_value_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.direct_costs_invested_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.total_budget_cost_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.labor_cost_pre_harvest_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.rent_fixed_only_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.commercial_cost_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.freight_cost_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.board_price_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.last_workorder_number_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.first_workorder_number_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.crop_incidence_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.total_costs_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.admin_cost_total_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.lease_invested_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.lease_executed_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.supply_movements_invested_total_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.direct_cost_per_ha_usd(p_labor_cost_usd numeric, p_supply_cost_usd numeric, p_sowed_area_ha numeric) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.last_stock_count_date_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.last_workorder_id_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.first_workorder_id_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.last_workorder_date_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.first_workorder_date_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.stock_value_for_project_mb(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.direct_costs_invested_for_project_mb(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.agrochemicals_invested_for_project_mb(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.seeds_invested_for_project_mb(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.cost_per_ha_for_crop_ssot(p_project_id bigint, p_crop_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.cost_per_ha_for_crop(p_project_id bigint, p_crop_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.total_costs_for_crop(p_project_id bigint, p_crop_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.supply_cost_received_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.supply_cost_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.total_invested_cost_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.operating_result_total_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.direct_costs_total_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.total_hectares_for_project(p_project_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.direct_cost_usd(p_labor_cost_usd numeric, p_supply_cost_usd numeric) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.renta_pct(operating_result_total_usd double precision, total_costs_usd double precision) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.harvested_area_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.seeded_area_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.yield_tn_per_ha_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.operating_result_per_ha_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.active_total_per_ha_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.rent_per_ha_for_lot_fixed(p_lot_id BIGINT) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.rent_per_ha_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.admin_cost_per_ha_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.cost_per_ha_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.direct_cost_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.income_net_per_ha_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.income_net_total_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.net_price_usd_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.supply_cost_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.kilograms_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.liters_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.surface_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.supply_cost_for_lot_by_category(p_lot_id bigint, p_category_name text) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.supply_cost_for_lot_base(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.labor_cost_for_lot(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.lot_tons(p_lot_id bigint) CASCADE;
DROP FUNCTION IF EXISTS v4_ssot.lot_hectares(p_lot_id bigint) CASCADE;
COMMIT;
