// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/alphacodinggroup/euxcel-backend/pkg/authe/jwt/v5"
	"github.com/alphacodinggroup/euxcel-backend/pkg/databases/cache/redis/v8"
	"github.com/alphacodinggroup/euxcel-backend/pkg/databases/nosql/mongodb/mongo-driver"
	"github.com/alphacodinggroup/euxcel-backend/pkg/databases/sql/gorm"
	"github.com/alphacodinggroup/euxcel-backend/pkg/databases/sql/postgresql/pgxpool"
	"github.com/alphacodinggroup/euxcel-backend/pkg/http/clients/resty"
	"github.com/alphacodinggroup/euxcel-backend/pkg/http/middlewares/gin"
	"github.com/alphacodinggroup/euxcel-backend/pkg/http/servers/gin"
	"github.com/alphacodinggroup/euxcel-backend/pkg/notification/smtp"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/authe"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/category"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/config"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/item"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/macrocategory"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/notification"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/person"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/supplier"
	"github.com/alphacodinggroup/euxcel-backend/projects/euxcel-api/internal/user"
)

// Injectors from wire.go:

// Initialize se encarga de inyectar todas las dependencias usando Wire.
func Initialize() (*Dependencies, error) {
	loader, err := ProvideConfigLoader()
	if err != nil {
		return nil, err
	}
	server, err := ProvideGinServer()
	if err != nil {
		return nil, err
	}
	repository, err := ProvideGormRepository()
	if err != nil {
		return nil, err
	}
	pkgmongoRepository, err := ProvideMongoDbRepository()
	if err != nil {
		return nil, err
	}
	pkgpostgresqlRepository, err := ProvidePostgresRepository()
	if err != nil {
		return nil, err
	}
	cache, err := ProvideRedisCache()
	if err != nil {
		return nil, err
	}
	service, err := ProvideJwtService()
	if err != nil {
		return nil, err
	}
	client, err := ProvideHttpClient()
	if err != nil {
		return nil, err
	}
	pkgsmtpService, err := ProvideSmtpService()
	if err != nil {
		return nil, err
	}
	handlerFunc, err := ProvideJwtMiddleware()
	if err != nil {
		return nil, err
	}
	middlewares, err := ProvideMiddlewares(handlerFunc)
	if err != nil {
		return nil, err
	}
	personRepository, err := ProvidePersonRepository(pkgpostgresqlRepository)
	if err != nil {
		return nil, err
	}
	useCases := ProvidePersonUseCases(personRepository)
	handler := ProvidePersonHandler(server, useCases, middlewares)
	userRepository, err := ProvideUserRepository(repository)
	if err != nil {
		return nil, err
	}
	userUseCases := ProvideUserUseCases(userRepository)
	userHandler := ProvideUserHandler(server, userUseCases, middlewares)
	autheCache, err := ProvideAutheCache(cache)
	if err != nil {
		return nil, err
	}
	jwtService, err := ProvideAutheJwtService(service, loader)
	if err != nil {
		return nil, err
	}
	httpClient, err := ProvideAutheHttpClient(client, loader)
	if err != nil {
		return nil, err
	}
	autheUseCases := ProvideAutheUseCases(autheCache, jwtService, httpClient)
	autheHandler := ProvideAutheHandler(server, autheUseCases, middlewares)
	smtpService, err := ProvideNotificationSmtpService(pkgsmtpService)
	if err != nil {
		return nil, err
	}
	notificationUseCases := ProvideNotificationUseCases(smtpService)
	notificationHandler := ProvideNotificationHandler(server, notificationUseCases, middlewares)
	itemRepository, err := ProvideItemRepository(repository)
	if err != nil {
		return nil, err
	}
	itemUseCases := ProvideItemUseCases(itemRepository, loader, autheUseCases)
	itemHandler := ProvideItemHandler(server, itemUseCases, middlewares)
	categoryRepository, err := ProvideCategoryRepository(repository)
	if err != nil {
		return nil, err
	}
	categoryUseCases := ProvideCategoryUseCases(categoryRepository)
	categoryHandler := ProvideCategoryHandler(server, categoryUseCases, middlewares)
	macrocategoryRepository, err := ProvideMacroCategoryRepository(repository)
	if err != nil {
		return nil, err
	}
	macrocategoryUseCases := ProvideMacroCategoryUseCases(macrocategoryRepository)
	macrocategoryHandler := ProvideMacroCategoryHandler(server, macrocategoryUseCases, middlewares)
	supplierRepository, err := ProvideSupplierRepository(repository)
	if err != nil {
		return nil, err
	}
	supplierUseCases := ProvideSupplierUseCases(supplierRepository)
	supplierHandler := ProvideSupplierHandler(server, supplierUseCases, middlewares)
	dependencies := &Dependencies{
		ConfigLoader:         loader,
		GinServer:            server,
		GormRepository:       repository,
		MongoRepository:      pkgmongoRepository,
		PostgresRepository:   pkgpostgresqlRepository,
		RedisCache:           cache,
		JwtService:           service,
		RestyClient:          client,
		SmtpService:          pkgsmtpService,
		Middlewares:          middlewares,
		PersonHandler:        handler,
		UserHandler:          userHandler,
		AutheHandler:         autheHandler,
		NotificationHandler:  notificationHandler,
		ItemHandler:          itemHandler,
		CategoryHandler:      categoryHandler,
		MacroCategoryHandler: macrocategoryHandler,
		SupplierHandler:      supplierHandler,
		PersonUseCases:       useCases,
		UserUseCases:         userUseCases,
		ItemUseCases:         itemUseCases,
	}
	return dependencies, nil
}

// wire.go:

// Dependencies reúne todas las dependencias de la aplicación que se inyectan con Wire.
type Dependencies struct {
	ConfigLoader       config.Loader
	GinServer          pkggin.Server
	GormRepository     pkggorm.Repository
	MongoRepository    pkgmongo.Repository
	PostgresRepository pkgpostgresql.Repository
	RedisCache         pkgredis.Cache
	JwtService         pkgjwt.Service
	RestyClient        pkcresty.Client
	SmtpService        pkgsmtp.Service

	Middlewares *pkgmwr.Middlewares

	PersonHandler        *person.Handler
	UserHandler          *user.Handler
	AutheHandler         *authe.Handler
	NotificationHandler  *notification.Handler
	ItemHandler          *item.Handler
	CategoryHandler      *category.Handler
	MacroCategoryHandler *macrocategory.Handler
	SupplierHandler      *supplier.Handler

	// Para pruebas
	PersonUseCases person.UseCases
	UserUseCases   user.UseCases
	ItemUseCases   item.UseCases
}
