// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/dashboard (interfaces: UseCasesPort,GinEnginePort,ConfigAPIPort,MiddlewaresEnginePort)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/dashboard/usecases/domain"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockUseCasesPort is a mock of UseCasesPort interface.
type MockUseCasesPort struct {
	ctrl     *gomock.Controller
	recorder *MockUseCasesPortMockRecorder
}

// MockUseCasesPortMockRecorder is the mock recorder for MockUseCasesPort.
type MockUseCasesPortMockRecorder struct {
	mock *MockUseCasesPort
}

// NewMockUseCasesPort creates a new mock instance.
func NewMockUseCasesPort(ctrl *gomock.Controller) *MockUseCasesPort {
	mock := &MockUseCasesPort{ctrl: ctrl}
	mock.recorder = &MockUseCasesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCasesPort) EXPECT() *MockUseCasesPortMockRecorder {
	return m.recorder
}

// GetDashboard mocks base method.
func (m *MockUseCasesPort) GetDashboard(arg0 context.Context, arg1 domain.DashboardFilter) (*domain.DashboardRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboard", arg0, arg1)
	ret0, _ := ret[0].(*domain.DashboardRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboard indicates an expected call of GetDashboard.
func (mr *MockUseCasesPortMockRecorder) GetDashboard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboard", reflect.TypeOf((*MockUseCasesPort)(nil).GetDashboard), arg0, arg1)
}

// MockGinEnginePort is a mock of GinEnginePort interface.
type MockGinEnginePort struct {
	ctrl     *gomock.Controller
	recorder *MockGinEnginePortMockRecorder
}

// MockGinEnginePortMockRecorder is the mock recorder for MockGinEnginePort.
type MockGinEnginePortMockRecorder struct {
	mock *MockGinEnginePort
}

// NewMockGinEnginePort creates a new mock instance.
func NewMockGinEnginePort(ctrl *gomock.Controller) *MockGinEnginePort {
	mock := &MockGinEnginePort{ctrl: ctrl}
	mock.recorder = &MockGinEnginePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGinEnginePort) EXPECT() *MockGinEnginePortMockRecorder {
	return m.recorder
}

// GetRouter mocks base method.
func (m *MockGinEnginePort) GetRouter() *gin.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouter")
	ret0, _ := ret[0].(*gin.Engine)
	return ret0
}

// GetRouter indicates an expected call of GetRouter.
func (mr *MockGinEnginePortMockRecorder) GetRouter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouter", reflect.TypeOf((*MockGinEnginePort)(nil).GetRouter))
}

// RunServer mocks base method.
func (m *MockGinEnginePort) RunServer(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunServer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunServer indicates an expected call of RunServer.
func (mr *MockGinEnginePortMockRecorder) RunServer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunServer", reflect.TypeOf((*MockGinEnginePort)(nil).RunServer), arg0)
}

// MockConfigAPIPort is a mock of ConfigAPIPort interface.
type MockConfigAPIPort struct {
	ctrl     *gomock.Controller
	recorder *MockConfigAPIPortMockRecorder
}

// MockConfigAPIPortMockRecorder is the mock recorder for MockConfigAPIPort.
type MockConfigAPIPortMockRecorder struct {
	mock *MockConfigAPIPort
}

// NewMockConfigAPIPort creates a new mock instance.
func NewMockConfigAPIPort(ctrl *gomock.Controller) *MockConfigAPIPort {
	mock := &MockConfigAPIPort{ctrl: ctrl}
	mock.recorder = &MockConfigAPIPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigAPIPort) EXPECT() *MockConfigAPIPortMockRecorder {
	return m.recorder
}

// APIBaseURL mocks base method.
func (m *MockConfigAPIPort) APIBaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIBaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// APIBaseURL indicates an expected call of APIBaseURL.
func (mr *MockConfigAPIPortMockRecorder) APIBaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIBaseURL", reflect.TypeOf((*MockConfigAPIPort)(nil).APIBaseURL))
}

// APIVersion mocks base method.
func (m *MockConfigAPIPort) APIVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// APIVersion indicates an expected call of APIVersion.
func (mr *MockConfigAPIPortMockRecorder) APIVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIVersion", reflect.TypeOf((*MockConfigAPIPort)(nil).APIVersion))
}

// MockMiddlewaresEnginePort is a mock of MiddlewaresEnginePort interface.
type MockMiddlewaresEnginePort struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewaresEnginePortMockRecorder
}

// MockMiddlewaresEnginePortMockRecorder is the mock recorder for MockMiddlewaresEnginePort.
type MockMiddlewaresEnginePortMockRecorder struct {
	mock *MockMiddlewaresEnginePort
}

// NewMockMiddlewaresEnginePort creates a new mock instance.
func NewMockMiddlewaresEnginePort(ctrl *gomock.Controller) *MockMiddlewaresEnginePort {
	mock := &MockMiddlewaresEnginePort{ctrl: ctrl}
	mock.recorder = &MockMiddlewaresEnginePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddlewaresEnginePort) EXPECT() *MockMiddlewaresEnginePortMockRecorder {
	return m.recorder
}

// GetGlobal mocks base method.
func (m *MockMiddlewaresEnginePort) GetGlobal() []gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobal")
	ret0, _ := ret[0].([]gin.HandlerFunc)
	return ret0
}

// GetGlobal indicates an expected call of GetGlobal.
func (mr *MockMiddlewaresEnginePortMockRecorder) GetGlobal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobal", reflect.TypeOf((*MockMiddlewaresEnginePort)(nil).GetGlobal))
}

// GetProtected mocks base method.
func (m *MockMiddlewaresEnginePort) GetProtected() []gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProtected")
	ret0, _ := ret[0].([]gin.HandlerFunc)
	return ret0
}

// GetProtected indicates an expected call of GetProtected.
func (mr *MockMiddlewaresEnginePortMockRecorder) GetProtected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProtected", reflect.TypeOf((*MockMiddlewaresEnginePort)(nil).GetProtected))
}

// GetValidation mocks base method.
func (m *MockMiddlewaresEnginePort) GetValidation() []gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidation")
	ret0, _ := ret[0].([]gin.HandlerFunc)
	return ret0
}

// GetValidation indicates an expected call of GetValidation.
func (mr *MockMiddlewaresEnginePortMockRecorder) GetValidation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidation", reflect.TypeOf((*MockMiddlewaresEnginePort)(nil).GetValidation))
}
