-- Este archivo limpia todas las tablas en el orden correcto (dependencias primero)
-- Limpiar tablas con dependencias primero
TRUNCATE TABLE workorder_items RESTART IDENTITY CASCADE;
TRUNCATE TABLE workorders RESTART IDENTITY CASCADE;
TRUNCATE TABLE invoices RESTART IDENTITY CASCADE;
TRUNCATE TABLE lot_dates RESTART IDENTITY CASCADE;
TRUNCATE TABLE lots RESTART IDENTITY CASCADE;
TRUNCATE TABLE fields RESTART IDENTITY CASCADE;
TRUNCATE TABLE project_dollar_values RESTART IDENTITY CASCADE;
TRUNCATE TABLE project_investors RESTART IDENTITY CASCADE;
TRUNCATE TABLE project_managers RESTART IDENTITY CASCADE;
TRUNCATE TABLE projects RESTART IDENTITY CASCADE;
TRUNCATE TABLE supplies RESTART IDENTITY CASCADE;
TRUNCATE TABLE labors RESTART IDENTITY CASCADE;
TRUNCATE TABLE labor_categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE labor_types RESTART IDENTITY CASCADE;
TRUNCATE TABLE categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE types RESTART IDENTITY CASCADE;
TRUNCATE TABLE units RESTART IDENTITY CASCADE;

-- Nuevas tablas agregadas
TRUNCATE TABLE supply_movements RESTART IDENTITY CASCADE;
TRUNCATE TABLE stocks RESTART IDENTITY CASCADE;
TRUNCATE TABLE providers RESTART IDENTITY CASCADE;
TRUNCATE TABLE crop_commercializations RESTART IDENTITY CASCADE;
TRUNCATE TABLE crops RESTART IDENTITY CASCADE;
TRUNCATE TABLE lease_types RESTART IDENTITY CASCADE;
TRUNCATE TABLE managers RESTART IDENTITY CASCADE;
TRUNCATE TABLE investors RESTART IDENTITY CASCADE;
TRUNCATE TABLE campaigns RESTART IDENTITY CASCADE;
TRUNCATE TABLE customers RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;

-- Reiniciar secuencias
ALTER SEQUENCE users_id_seq RESTART WITH 1;
ALTER SEQUENCE campaigns_id_seq RESTART WITH 1;
ALTER SEQUENCE customers_id_seq RESTART WITH 1;
ALTER SEQUENCE managers_id_seq RESTART WITH 1;
ALTER SEQUENCE investors_id_seq RESTART WITH 1;
ALTER SEQUENCE crops_id_seq RESTART WITH 1;
ALTER SEQUENCE lease_types_id_seq RESTART WITH 1;
ALTER SEQUENCE projects_id_seq RESTART WITH 1;
ALTER SEQUENCE fields_id_seq RESTART WITH 1;
ALTER SEQUENCE lots_id_seq RESTART WITH 1;
ALTER SEQUENCE labor_types_id_seq RESTART WITH 1;
ALTER SEQUENCE labor_categories_id_seq RESTART WITH 1;
ALTER SEQUENCE types_id_seq RESTART WITH 1;
ALTER SEQUENCE categories_id_seq RESTART WITH 1;
ALTER SEQUENCE units_id_seq RESTART WITH 1;
ALTER SEQUENCE supplies_id_seq RESTART WITH 1;
ALTER SEQUENCE labors_id_seq RESTART WITH 1;
ALTER SEQUENCE providers_id_seq RESTART WITH 1;
ALTER SEQUENCE stocks_id_seq RESTART WITH 1;
ALTER SEQUENCE supply_movements_id_seq RESTART WITH 1;
ALTER SEQUENCE workorders_id_seq RESTART WITH 1;
ALTER SEQUENCE workorder_items_id_seq RESTART WITH 1;
ALTER SEQUENCE invoices_id_seq RESTART WITH 1;
ALTER SEQUENCE lot_dates_id_seq RESTART WITH 1;
ALTER SEQUENCE crop_commercializations_id_seq RESTART WITH 1;

-- Verificar limpieza
SELECT '✅ Base de datos limpiada' as status; 