FROM golang:1.26.1-alpine

ENV TZ=America/Argentina/Buenos_Aires
RUN apk add --no-cache \
   tzdata \
   sqlite \
   sqlite-dev \
   gcc \
   musl-dev \
   git

RUN go install github.com/air-verse/air@latest

WORKDIR /app

# En dev, go.mod y el código se montan como volumen.
# go mod download se ejecuta al iniciar el container, no en build.
EXPOSE 8080

CMD ["sh", "-c", "go mod download && CGO_ENABLED=1 go build -buildvcs=false -o /tmp/migrate_binary ./cmd/migrate/ && /tmp/migrate_binary && air -c .air.toml"]
