-- ========================================
-- MIGRATION 000080 CONSTRAINTS FKS INDEXES (DOWN)
-- ========================================
-- Nota: SQL en inglés, comentarios en español

BEGIN;

-- INDEXES
DROP INDEX IF EXISTS idx_project_dollar_values_project_id;
DROP INDEX IF EXISTS idx_crop_commercializations_notdel;
DROP INDEX IF EXISTS idx_crop_commercializations_project_id;
DROP INDEX IF EXISTS idx_crop_commercializations_deleted_at;
DROP INDEX IF EXISTS idx_crop_commercializations_crop_id;
DROP INDEX IF EXISTS idx_field_investors_investor_id;
DROP INDEX IF EXISTS idx_admin_cost_investors_investor_id;
DROP INDEX IF EXISTS idx_project_investors_deleted_by;
DROP INDEX IF EXISTS idx_project_investors_updated_by;
DROP INDEX IF EXISTS idx_project_investors_created_by;
DROP INDEX IF EXISTS idx_project_investors_investor_id;
DROP INDEX IF EXISTS idx_investors_deleted_by;
DROP INDEX IF EXISTS idx_investors_updated_by;
DROP INDEX IF EXISTS idx_investors_created_by;
DROP INDEX IF EXISTS idx_supply_movements_investor_id;
DROP INDEX IF EXISTS idx_supply_movements_provider_id;
DROP INDEX IF EXISTS idx_supply_movements_supply_id;
DROP INDEX IF EXISTS idx_stocks_investor_id;
DROP INDEX IF EXISTS idx_stocks_supply_id;
DROP INDEX IF EXISTS idx_stocks_project_id;
DROP INDEX IF EXISTS idx_categories_type_id;
DROP INDEX IF EXISTS idx_supplies_type_id;
DROP INDEX IF EXISTS idx_supplies_category_id;
DROP INDEX IF EXISTS idx_supplies_units_notdel;
DROP INDEX IF EXISTS idx_supplies_notdel;
DROP INDEX IF EXISTS idx_workorder_items_workorder_id;
DROP INDEX IF EXISTS idx_workorder_items_supply_id;
DROP INDEX IF EXISTS idx_workorder_items_v2_notdel;
DROP INDEX IF EXISTS idx_workorder_items_supply_notdel;
DROP INDEX IF EXISTS idx_workorder_items_notdel;
DROP INDEX IF EXISTS idx_workorders_lot_notdel;
DROP INDEX IF EXISTS idx_workorders_lot_composite;
DROP INDEX IF EXISTS idx_workorders_metrics_notdel;
DROP INDEX IF EXISTS idx_workorders_composite;
DROP INDEX IF EXISTS idx_workorders_grouping;
DROP INDEX IF EXISTS idx_workorders_labor_id;
DROP INDEX IF EXISTS idx_workorders_crop_id;
DROP INDEX IF EXISTS idx_workorders_field_id;
DROP INDEX IF EXISTS idx_labors_sowing;
DROP INDEX IF EXISTS idx_labors_notdel_price;
DROP INDEX IF EXISTS idx_labors_harvest;
DROP INDEX IF EXISTS idx_labors_project_id;
DROP INDEX IF EXISTS idx_labors_category_id;
DROP INDEX IF EXISTS idx_labors_notdel;
DROP INDEX IF EXISTS idx_crops_notdel;
DROP INDEX IF EXISTS idx_crops_deleted_by;
DROP INDEX IF EXISTS idx_crops_updated_by;
DROP INDEX IF EXISTS idx_crops_created_by;
DROP INDEX IF EXISTS idx_lots_previous_crop_id;
DROP INDEX IF EXISTS idx_lots_field_id;
DROP INDEX IF EXISTS idx_lots_current_crop_id;
DROP INDEX IF EXISTS idx_lots_notdel;
DROP INDEX IF EXISTS idx_lots_composite_notdel;
DROP INDEX IF EXISTS idx_lots_deleted_by;
DROP INDEX IF EXISTS idx_lots_updated_by;
DROP INDEX IF EXISTS idx_lots_created_by;
DROP INDEX IF EXISTS idx_fields_notdel;
DROP INDEX IF EXISTS idx_fields_project_id;
DROP INDEX IF EXISTS idx_fields_deleted_by;
DROP INDEX IF EXISTS idx_fields_updated_by;
DROP INDEX IF EXISTS idx_fields_created_by;
DROP INDEX IF EXISTS idx_fields_lease_type_id;
DROP INDEX IF EXISTS idx_lease_types_deleted_by;
DROP INDEX IF EXISTS idx_lease_types_updated_by;
DROP INDEX IF EXISTS idx_lease_types_created_by;
DROP INDEX IF EXISTS idx_project_managers_deleted_by;
DROP INDEX IF EXISTS idx_project_managers_updated_by;
DROP INDEX IF EXISTS idx_project_managers_created_by;
DROP INDEX IF EXISTS idx_project_managers_manager_id;
DROP INDEX IF EXISTS idx_managers_deleted_by;
DROP INDEX IF EXISTS idx_managers_updated_by;
DROP INDEX IF EXISTS idx_managers_created_by;
DROP INDEX IF EXISTS idx_projects_deleted_by;
DROP INDEX IF EXISTS idx_projects_updated_by;
DROP INDEX IF EXISTS idx_projects_created_by;
DROP INDEX IF EXISTS idx_projects_active;
DROP INDEX IF EXISTS idx_projects_customer_id;
DROP INDEX IF EXISTS idx_projects_campaign_id;
DROP INDEX IF EXISTS idx_projects_notdel;
DROP INDEX IF EXISTS idx_campaigns_deleted_by;
DROP INDEX IF EXISTS idx_campaigns_updated_by;
DROP INDEX IF EXISTS idx_campaigns_created_by;
DROP INDEX IF EXISTS idx_customers_deleted_by;
DROP INDEX IF EXISTS idx_customers_updated_by;
DROP INDEX IF EXISTS idx_customers_created_by;
DROP INDEX IF EXISTS idx_labor_categories_type_id;
DROP INDEX IF EXISTS idx_lot_dates_deleted_by;
DROP INDEX IF EXISTS idx_lot_dates_updated_by;
DROP INDEX IF EXISTS idx_lot_dates_created_by;
DROP INDEX IF EXISTS idx_lot_dates_lot_id;
DROP INDEX IF EXISTS idx_fx_rates_effective_date;
DROP INDEX IF EXISTS idx_business_parameters_key;
DROP INDEX IF EXISTS idx_business_parameters_category;
DROP INDEX IF EXISTS idx_users_deleted_at;

-- FOREIGN KEYS
ALTER TABLE ONLY public.invoices DROP CONSTRAINT IF EXISTS fk_invoices_work_order;
ALTER TABLE ONLY public.project_dollar_values DROP CONSTRAINT IF EXISTS fk_project_dollar_values_project;
ALTER TABLE ONLY public.field_investors DROP CONSTRAINT IF EXISTS fk_field_investors_investor;
ALTER TABLE ONLY public.field_investors DROP CONSTRAINT IF EXISTS fk_field_investors_field;
ALTER TABLE ONLY public.admin_cost_investors DROP CONSTRAINT IF EXISTS fk_admin_cost_investors_investor;
ALTER TABLE ONLY public.admin_cost_investors DROP CONSTRAINT IF EXISTS fk_admin_cost_investors_project;
ALTER TABLE ONLY public.crop_commercializations DROP CONSTRAINT IF EXISTS fk_crop_commercializations_crop;
ALTER TABLE ONLY public.crop_commercializations DROP CONSTRAINT IF EXISTS fk_crop_commercializations_project;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_deleted_by;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_updated_by;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_created_by;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_investor;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_project;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS fk_investors_deleted_by;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS fk_investors_updated_by;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS fk_investors_created_by;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS fk_supply_movements_investor;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS fk_supply_movements_provider;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS fk_supply_movements_supply;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS fk_stocks_investor;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS fk_stocks_supply;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS fk_stocks_project;
ALTER TABLE ONLY public.supplies DROP CONSTRAINT IF EXISTS fk_supplies_type;
ALTER TABLE ONLY public.supplies DROP CONSTRAINT IF EXISTS fk_supplies_category;
ALTER TABLE ONLY public.categories DROP CONSTRAINT IF EXISTS fk_categories_type;
ALTER TABLE ONLY public.workorder_items DROP CONSTRAINT IF EXISTS fk_workorder_items_supply;
ALTER TABLE ONLY public.workorder_items DROP CONSTRAINT IF EXISTS fk_workorder_items_workorder;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS fk_workorders_labor;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS fk_workorders_crop;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS fk_workorders_lot;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS fk_workorders_field;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS fk_workorders_project;
ALTER TABLE ONLY public.labors DROP CONSTRAINT IF EXISTS fk_labors_category;
ALTER TABLE ONLY public.labors DROP CONSTRAINT IF EXISTS fk_labors_project;
ALTER TABLE ONLY public.labor_categories DROP CONSTRAINT IF EXISTS fk_labor_categories_type;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS fk_crops_deleted_by;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS fk_crops_updated_by;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS fk_crops_created_by;
ALTER TABLE ONLY public.lot_dates DROP CONSTRAINT IF EXISTS fk_lot_dates_deleted_by;
ALTER TABLE ONLY public.lot_dates DROP CONSTRAINT IF EXISTS fk_lot_dates_updated_by;
ALTER TABLE ONLY public.lot_dates DROP CONSTRAINT IF EXISTS fk_lot_dates_created_by;
ALTER TABLE ONLY public.lot_dates DROP CONSTRAINT IF EXISTS fk_lot_dates_lot;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_deleted_by;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_updated_by;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_created_by;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_previous_crop;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_current_crop;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_field;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_deleted_by;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_updated_by;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_created_by;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_lease_type;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_project;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS fk_lease_types_deleted_by;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS fk_lease_types_updated_by;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS fk_lease_types_created_by;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_deleted_by;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_updated_by;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_created_by;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_manager;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_project;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS fk_managers_deleted_by;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS fk_managers_updated_by;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS fk_managers_created_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_deleted_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_updated_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_created_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_campaign;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_customer;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS fk_campaigns_deleted_by;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS fk_campaigns_updated_by;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS fk_campaigns_created_by;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS fk_customers_deleted_by;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS fk_customers_updated_by;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS fk_customers_created_by;

-- UNIQUE
ALTER TABLE ONLY public.invoices DROP CONSTRAINT IF EXISTS uq_invoices_work_order;
ALTER TABLE ONLY public.project_dollar_values DROP CONSTRAINT IF EXISTS uq_project_dollar_values_period;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS uq_investors_name;
ALTER TABLE ONLY public.providers DROP CONSTRAINT IF EXISTS uq_providers_name;
ALTER TABLE ONLY public.types DROP CONSTRAINT IF EXISTS uq_types_name;
ALTER TABLE ONLY public.labor_types DROP CONSTRAINT IF EXISTS uq_labor_types_name;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS uq_crops_name;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS uq_lease_types_name;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS uq_managers_name;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS uq_campaigns_name;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS uq_customers_name;
ALTER TABLE ONLY public.fx_rates DROP CONSTRAINT IF EXISTS uq_fx_rates_pair_date;
ALTER TABLE ONLY public.business_parameters DROP CONSTRAINT IF EXISTS uq_business_parameters_key;
ALTER TABLE ONLY public.users DROP CONSTRAINT IF EXISTS uq_users_username;

-- PRIMARY KEYS
ALTER TABLE ONLY public.invoices DROP CONSTRAINT IF EXISTS pk_invoices;
ALTER TABLE ONLY public.project_dollar_values DROP CONSTRAINT IF EXISTS pk_project_dollar_values;
ALTER TABLE ONLY public.field_investors DROP CONSTRAINT IF EXISTS pk_field_investors;
ALTER TABLE ONLY public.admin_cost_investors DROP CONSTRAINT IF EXISTS pk_admin_cost_investors;
ALTER TABLE ONLY public.crop_commercializations DROP CONSTRAINT IF EXISTS pk_crop_commercializations;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS pk_project_investors;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS pk_investors;
ALTER TABLE ONLY public.providers DROP CONSTRAINT IF EXISTS pk_providers;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS pk_supply_movements;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS pk_stocks;
ALTER TABLE ONLY public.supplies DROP CONSTRAINT IF EXISTS pk_supplies;
ALTER TABLE ONLY public.categories DROP CONSTRAINT IF EXISTS pk_categories;
ALTER TABLE ONLY public.types DROP CONSTRAINT IF EXISTS pk_types;
ALTER TABLE ONLY public.workorder_items DROP CONSTRAINT IF EXISTS pk_workorder_items;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS pk_workorders;
ALTER TABLE ONLY public.labors DROP CONSTRAINT IF EXISTS pk_labors;
ALTER TABLE ONLY public.labor_categories DROP CONSTRAINT IF EXISTS pk_labor_categories;
ALTER TABLE ONLY public.labor_types DROP CONSTRAINT IF EXISTS pk_labor_types;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS pk_crops;
ALTER TABLE ONLY public.lot_dates DROP CONSTRAINT IF EXISTS pk_lot_dates;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS pk_lots;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS pk_fields;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS pk_lease_types;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS pk_project_managers;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS pk_managers;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS pk_projects;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS pk_campaigns;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS pk_customers;
ALTER TABLE ONLY public.fx_rates DROP CONSTRAINT IF EXISTS pk_fx_rates;
ALTER TABLE ONLY public.business_parameters DROP CONSTRAINT IF EXISTS pk_business_parameters;
ALTER TABLE ONLY public.users DROP CONSTRAINT IF EXISTS pk_users;

COMMIT;
