// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devpablocristo/ponti-backend/internal/stock (interfaces: UseCasesPort)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/devpablocristo/ponti-backend/internal/stock/usecases/domain"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockUseCasesPort is a mock of UseCasesPort interface.
type MockUseCasesPort struct {
	ctrl     *gomock.Controller
	recorder *MockUseCasesPortMockRecorder
}

// MockUseCasesPortMockRecorder is the mock recorder for MockUseCasesPort.
type MockUseCasesPortMockRecorder struct {
	mock *MockUseCasesPort
}

// NewMockUseCasesPort creates a new mock instance.
func NewMockUseCasesPort(ctrl *gomock.Controller) *MockUseCasesPort {
	mock := &MockUseCasesPort{ctrl: ctrl}
	mock.recorder = &MockUseCasesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCasesPort) EXPECT() *MockUseCasesPortMockRecorder {
	return m.recorder
}

// CreateStock mocks base method.
func (m *MockUseCasesPort) CreateStock(arg0 context.Context, arg1 *domain.Stock) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStock", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStock indicates an expected call of CreateStock.
func (mr *MockUseCasesPortMockRecorder) CreateStock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStock", reflect.TypeOf((*MockUseCasesPort)(nil).CreateStock), arg0, arg1)
}

// ExportStocksByProject mocks base method.
func (m *MockUseCasesPort) ExportStocksByProject(arg0 context.Context, arg1 int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportStocksByProject", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportStocksByProject indicates an expected call of ExportStocksByProject.
func (mr *MockUseCasesPortMockRecorder) ExportStocksByProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportStocksByProject", reflect.TypeOf((*MockUseCasesPort)(nil).ExportStocksByProject), arg0, arg1)
}

// GetLastStockByProjectID mocks base method.
func (m *MockUseCasesPort) GetLastStockByProjectID(arg0 context.Context, arg1, arg2 int64) (*domain.Stock, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastStockByProjectID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastStockByProjectID indicates an expected call of GetLastStockByProjectID.
func (mr *MockUseCasesPortMockRecorder) GetLastStockByProjectID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastStockByProjectID", reflect.TypeOf((*MockUseCasesPort)(nil).GetLastStockByProjectID), arg0, arg1, arg2)
}

// GetLastStockByProjectInvestorID mocks base method.
func (m *MockUseCasesPort) GetLastStockByProjectInvestorID(arg0 context.Context, arg1, arg2, arg3 int64) (*domain.Stock, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastStockByProjectInvestorID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastStockByProjectInvestorID indicates an expected call of GetLastStockByProjectInvestorID.
func (mr *MockUseCasesPortMockRecorder) GetLastStockByProjectInvestorID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastStockByProjectInvestorID", reflect.TypeOf((*MockUseCasesPort)(nil).GetLastStockByProjectInvestorID), arg0, arg1, arg2, arg3)
}

// GetStockByID mocks base method.
func (m *MockUseCasesPort) GetStockByID(arg0 context.Context, arg1 int64) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockByID indicates an expected call of GetStockByID.
func (mr *MockUseCasesPortMockRecorder) GetStockByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockByID", reflect.TypeOf((*MockUseCasesPort)(nil).GetStockByID), arg0, arg1)
}

// GetStocksPeriods mocks base method.
func (m *MockUseCasesPort) GetStocksPeriods(arg0 context.Context, arg1 int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocksPeriods", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocksPeriods indicates an expected call of GetStocksPeriods.
func (mr *MockUseCasesPortMockRecorder) GetStocksPeriods(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocksPeriods", reflect.TypeOf((*MockUseCasesPort)(nil).GetStocksPeriods), arg0, arg1)
}

// GetStocksSummary mocks base method.
func (m *MockUseCasesPort) GetStocksSummary(arg0 context.Context, arg1 int64, arg2 time.Time) ([]*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocksSummary", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocksSummary indicates an expected call of GetStocksSummary.
func (mr *MockUseCasesPortMockRecorder) GetStocksSummary(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocksSummary", reflect.TypeOf((*MockUseCasesPort)(nil).GetStocksSummary), arg0, arg1, arg2)
}

// GetStockBySupplyID mocks base method.
func (m *MockUseCasesPort) GetStockBySupplyID(arg0 context.Context, arg1, arg2 int64, arg3 time.Time) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockBySupplyID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockBySupplyID indicates an expected call of GetStockBySupplyID.
func (mr *MockUseCasesPortMockRecorder) GetStockBySupplyID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockBySupplyID", reflect.TypeOf((*MockUseCasesPort)(nil).GetStockBySupplyID), arg0, arg1, arg2, arg3)
}

// UpdateCloseDateByProject mocks base method.
func (m *MockUseCasesPort) UpdateCloseDateByProject(arg0 context.Context, arg1, arg2, arg3 int64, arg4 *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCloseDateByProject", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCloseDateByProject indicates an expected call of UpdateCloseDateByProject.
func (mr *MockUseCasesPortMockRecorder) UpdateCloseDateByProject(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCloseDateByProject", reflect.TypeOf((*MockUseCasesPort)(nil).UpdateCloseDateByProject), arg0, arg1, arg2, arg3, arg4)
}

// UpdateRealStockUnits mocks base method.
func (m *MockUseCasesPort) UpdateRealStockUnits(arg0 context.Context, arg1 int64, arg2 *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRealStockUnits", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRealStockUnits indicates an expected call of UpdateRealStockUnits.
func (mr *MockUseCasesPortMockRecorder) UpdateRealStockUnits(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRealStockUnits", reflect.TypeOf((*MockUseCasesPort)(nil).UpdateRealStockUnits), arg0, arg1, arg2)
}

// UpdateUnitsConsumed mocks base method.
func (m *MockUseCasesPort) UpdateUnitsConsumed(arg0 context.Context, arg1 domain.Stock, arg2 decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUnitsConsumed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUnitsConsumed indicates an expected call of UpdateUnitsConsumed.
func (mr *MockUseCasesPortMockRecorder) UpdateUnitsConsumed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUnitsConsumed", reflect.TypeOf((*MockUseCasesPort)(nil).UpdateUnitsConsumed), arg0, arg1, arg2)
}
