// Code generated by MockGen. DO NOT EDIT.
// Source: /home/pablo/Projects/Pablo/ponti-backend/internal/supply/usecases.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain2 "github.com/alphacodinggroup/ponti-backend/internal/investor/usecases/domain"
	domain "github.com/alphacodinggroup/ponti-backend/internal/provider/usecases/domain"
	domain0 "github.com/alphacodinggroup/ponti-backend/internal/stock/usecases/domain"
	domain1 "github.com/alphacodinggroup/ponti-backend/internal/supply/usecases/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryPort is a mock of RepositoryPort interface.
type MockRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryPortMockRecorder
}

// MockRepositoryPortMockRecorder is the mock recorder for MockRepositoryPort.
type MockRepositoryPortMockRecorder struct {
	mock *MockRepositoryPort
}

// NewMockRepositoryPort creates a new mock instance.
func NewMockRepositoryPort(ctrl *gomock.Controller) *MockRepositoryPort {
	mock := &MockRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryPort) EXPECT() *MockRepositoryPortMockRecorder {
	return m.recorder
}

// CreateProvider mocks base method.
func (m *MockRepositoryPort) CreateProvider(arg0 context.Context, arg1 *domain.Provider) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvider", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProvider indicates an expected call of CreateProvider.
func (mr *MockRepositoryPortMockRecorder) CreateProvider(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvider", reflect.TypeOf((*MockRepositoryPort)(nil).CreateProvider), arg0, arg1)
}

// CreateSuppliesBulk mocks base method.
func (m *MockRepositoryPort) CreateSuppliesBulk(arg0 context.Context, arg1 []domain1.Supply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSuppliesBulk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSuppliesBulk indicates an expected call of CreateSuppliesBulk.
func (mr *MockRepositoryPortMockRecorder) CreateSuppliesBulk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSuppliesBulk", reflect.TypeOf((*MockRepositoryPort)(nil).CreateSuppliesBulk), arg0, arg1)
}

// CreateSupply mocks base method.
func (m *MockRepositoryPort) CreateSupply(arg0 context.Context, arg1 *domain1.Supply) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupply", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSupply indicates an expected call of CreateSupply.
func (mr *MockRepositoryPortMockRecorder) CreateSupply(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupply", reflect.TypeOf((*MockRepositoryPort)(nil).CreateSupply), arg0, arg1)
}

// CreateSupplyMovement mocks base method.
func (m *MockRepositoryPort) CreateSupplyMovement(arg0 context.Context, arg1 *domain1.SupplyMovement) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupplyMovement", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSupplyMovement indicates an expected call of CreateSupplyMovement.
func (mr *MockRepositoryPortMockRecorder) CreateSupplyMovement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupplyMovement", reflect.TypeOf((*MockRepositoryPort)(nil).CreateSupplyMovement), arg0, arg1)
}

// DeleteSupply mocks base method.
func (m *MockRepositoryPort) DeleteSupply(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupply", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSupply indicates an expected call of DeleteSupply.
func (mr *MockRepositoryPortMockRecorder) DeleteSupply(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupply", reflect.TypeOf((*MockRepositoryPort)(nil).DeleteSupply), arg0, arg1)
}

// DeleteSupplyMovement mocks base method.
func (m *MockRepositoryPort) DeleteSupplyMovement(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplyMovement", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSupplyMovement indicates an expected call of DeleteSupplyMovement.
func (mr *MockRepositoryPortMockRecorder) DeleteSupplyMovement(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplyMovement", reflect.TypeOf((*MockRepositoryPort)(nil).DeleteSupplyMovement), arg0, arg1, arg2)
}

// ExecuteInTransaction mocks base method.
func (m *MockRepositoryPort) ExecuteInTransaction(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteInTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteInTransaction indicates an expected call of ExecuteInTransaction.
func (mr *MockRepositoryPortMockRecorder) ExecuteInTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteInTransaction", reflect.TypeOf((*MockRepositoryPort)(nil).ExecuteInTransaction), arg0, arg1)
}

// GetEntriesSupplyMovementsByProjectID mocks base method.
func (m *MockRepositoryPort) GetEntriesSupplyMovementsByProjectID(arg0 context.Context, arg1 int64) ([]*domain1.SupplyMovement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesSupplyMovementsByProjectID", arg0, arg1)
	ret0, _ := ret[0].([]*domain1.SupplyMovement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesSupplyMovementsByProjectID indicates an expected call of GetEntriesSupplyMovementsByProjectID.
func (mr *MockRepositoryPortMockRecorder) GetEntriesSupplyMovementsByProjectID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesSupplyMovementsByProjectID", reflect.TypeOf((*MockRepositoryPort)(nil).GetEntriesSupplyMovementsByProjectID), arg0, arg1)
}

// GetProviders mocks base method.
func (m *MockRepositoryPort) GetProviders(arg0 context.Context) ([]domain.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviders", arg0)
	ret0, _ := ret[0].([]domain.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviders indicates an expected call of GetProviders.
func (mr *MockRepositoryPortMockRecorder) GetProviders(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviders", reflect.TypeOf((*MockRepositoryPort)(nil).GetProviders), arg0)
}

// GetProvider mocks base method.
func (m *MockRepositoryPort) GetProvider(arg0 context.Context, arg1 int64) (*domain.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider", arg0, arg1)
	ret0, _ := ret[0].(*domain.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockRepositoryPortMockRecorder) GetProvider(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockRepositoryPort)(nil).GetProvider), arg0, arg1)
}

// GetInvestor mocks base method.
func (m *MockRepositoryPort) GetInvestor(arg0 context.Context, arg1 int64) (*domain2.Investor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvestor", arg0, arg1)
	ret0, _ := ret[0].(*domain2.Investor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvestor indicates an expected call of GetInvestor.
func (mr *MockRepositoryPortMockRecorder) GetInvestor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvestor", reflect.TypeOf((*MockRepositoryPort)(nil).GetInvestor), arg0, arg1)
}

// GetSupply mocks base method.
func (m *MockRepositoryPort) GetSupply(arg0 context.Context, arg1 int64) (*domain1.Supply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupply", arg0, arg1)
	ret0, _ := ret[0].(*domain1.Supply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupply indicates an expected call of GetSupply.
func (mr *MockRepositoryPortMockRecorder) GetSupply(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupply", reflect.TypeOf((*MockRepositoryPort)(nil).GetSupply), arg0, arg1)
}

// GetSuppliesByIDs mocks base method.
func (m *MockRepositoryPort) GetSuppliesByIDs(arg0 context.Context, arg1 []int64) ([]domain1.Supply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuppliesByIDs", arg0, arg1)
	ret0, _ := ret[0].([]domain1.Supply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuppliesByIDs indicates an expected call of GetSuppliesByIDs.
func (mr *MockRepositoryPortMockRecorder) GetSuppliesByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuppliesByIDs", reflect.TypeOf((*MockRepositoryPort)(nil).GetSuppliesByIDs), arg0, arg1)
}

// GetSupplyByProjectAndName mocks base method.
func (m *MockRepositoryPort) GetSupplyByProjectAndName(arg0 context.Context, arg1 int64, arg2 string) (*domain1.Supply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplyByProjectAndName", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain1.Supply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplyByProjectAndName indicates an expected call of GetSupplyByProjectAndName.
func (mr *MockRepositoryPortMockRecorder) GetSupplyByProjectAndName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplyByProjectAndName", reflect.TypeOf((*MockRepositoryPort)(nil).GetSupplyByProjectAndName), arg0, arg1, arg2)
}

// GetSupplyMovementByID mocks base method.
func (m *MockRepositoryPort) GetSupplyMovementByID(arg0 context.Context, arg1 int64) (*domain1.SupplyMovement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplyMovementByID", arg0, arg1)
	ret0, _ := ret[0].(*domain1.SupplyMovement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplyMovementByID indicates an expected call of GetSupplyMovementByID.
func (mr *MockRepositoryPortMockRecorder) GetSupplyMovementByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplyMovementByID", reflect.TypeOf((*MockRepositoryPort)(nil).GetSupplyMovementByID), arg0, arg1)
}

// ExistsSupplyMovementByProjectReferenceAndSupply mocks base method.
func (m *MockRepositoryPort) ExistsSupplyMovementByProjectReferenceAndSupply(arg0 context.Context, arg1 int64, arg2 string, arg3 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsSupplyMovementByProjectReferenceAndSupply", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsSupplyMovementByProjectReferenceAndSupply indicates an expected call of ExistsSupplyMovementByProjectReferenceAndSupply.
func (mr *MockRepositoryPortMockRecorder) ExistsSupplyMovementByProjectReferenceAndSupply(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsSupplyMovementByProjectReferenceAndSupply", reflect.TypeOf((*MockRepositoryPort)(nil).ExistsSupplyMovementByProjectReferenceAndSupply), arg0, arg1, arg2, arg3)
}

// GetWorkOrdersBySupplyID mocks base method.
func (m *MockRepositoryPort) GetWorkOrdersBySupplyID(ctx context.Context, supplyID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkOrdersBySupplyID", ctx, supplyID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkOrdersBySupplyID indicates an expected call of GetWorkOrdersBySupplyID.
func (mr *MockRepositoryPortMockRecorder) GetWorkOrdersBySupplyID(ctx, supplyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkOrdersBySupplyID", reflect.TypeOf((*MockRepositoryPort)(nil).GetWorkOrdersBySupplyID), ctx, supplyID)
}

// ListAllSupplies mocks base method.
func (m *MockRepositoryPort) ListAllSupplies(arg0 context.Context, arg1 domain1.SupplyFilter) ([]domain1.Supply, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllSupplies", arg0, arg1)
	ret0, _ := ret[0].([]domain1.Supply)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAllSupplies indicates an expected call of ListAllSupplies.
func (mr *MockRepositoryPortMockRecorder) ListAllSupplies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllSupplies", reflect.TypeOf((*MockRepositoryPort)(nil).ListAllSupplies), arg0, arg1)
}

// ListSuppliesPaginated mocks base method.
func (m *MockRepositoryPort) ListSuppliesPaginated(arg0 context.Context, arg1 domain1.SupplyFilter, arg2 string, arg3, arg4 int) ([]domain1.Supply, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSuppliesPaginated", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]domain1.Supply)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSuppliesPaginated indicates an expected call of ListSuppliesPaginated.
func (mr *MockRepositoryPortMockRecorder) ListSuppliesPaginated(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSuppliesPaginated", reflect.TypeOf((*MockRepositoryPort)(nil).ListSuppliesPaginated), arg0, arg1, arg2, arg3, arg4)
}

// UpdateSuppliesBulk mocks base method.
func (m *MockRepositoryPort) UpdateSuppliesBulk(arg0 context.Context, arg1 []domain1.Supply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSuppliesBulk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSuppliesBulk indicates an expected call of UpdateSuppliesBulk.
func (mr *MockRepositoryPortMockRecorder) UpdateSuppliesBulk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuppliesBulk", reflect.TypeOf((*MockRepositoryPort)(nil).UpdateSuppliesBulk), arg0, arg1)
}

// UpdateSupply mocks base method.
func (m *MockRepositoryPort) UpdateSupply(arg0 context.Context, arg1 *domain1.Supply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupply", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSupply indicates an expected call of UpdateSupply.
func (mr *MockRepositoryPortMockRecorder) UpdateSupply(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupply", reflect.TypeOf((*MockRepositoryPort)(nil).UpdateSupply), arg0, arg1)
}

// UpdateSupplyMovement mocks base method.
func (m *MockRepositoryPort) UpdateSupplyMovement(arg0 context.Context, arg1 *domain1.SupplyMovement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupplyMovement", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSupplyMovement indicates an expected call of UpdateSupplyMovement.
func (mr *MockRepositoryPortMockRecorder) UpdateSupplyMovement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupplyMovement", reflect.TypeOf((*MockRepositoryPort)(nil).UpdateSupplyMovement), arg0, arg1)
}

// MockExporterAdapterPort is a mock of ExporterAdapterPort interface.
type MockExporterAdapterPort struct {
	ctrl     *gomock.Controller
	recorder *MockExporterAdapterPortMockRecorder
}

// MockExporterAdapterPortMockRecorder is the mock recorder for MockExporterAdapterPort.
type MockExporterAdapterPortMockRecorder struct {
	mock *MockExporterAdapterPort
}

// NewMockExporterAdapterPort creates a new mock instance.
func NewMockExporterAdapterPort(ctrl *gomock.Controller) *MockExporterAdapterPort {
	mock := &MockExporterAdapterPort{ctrl: ctrl}
	mock.recorder = &MockExporterAdapterPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExporterAdapterPort) EXPECT() *MockExporterAdapterPortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockExporterAdapterPort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockExporterAdapterPortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockExporterAdapterPort)(nil).Close))
}

// ExportSupplies mocks base method.
func (m *MockExporterAdapterPort) ExportSupplies(ctx context.Context, items []*domain1.Supply) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportSupplies", ctx, items)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportSupplies indicates an expected call of ExportSupplies.
func (mr *MockExporterAdapterPortMockRecorder) ExportSupplies(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportSupplies", reflect.TypeOf((*MockExporterAdapterPort)(nil).ExportSupplies), ctx, items)
}

// ExportSupplyMovements mocks base method.
func (m *MockExporterAdapterPort) ExportSupplyMovements(ctx context.Context, items []*domain1.SupplyMovement) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportSupplyMovements", ctx, items)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportSupplyMovements indicates an expected call of ExportSupplyMovements.
func (mr *MockExporterAdapterPortMockRecorder) ExportSupplyMovements(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportSupplyMovements", reflect.TypeOf((*MockExporterAdapterPort)(nil).ExportSupplyMovements), ctx, items)
}

// MockStockUseCasesPort is a mock of StockUseCasesPort interface.
type MockStockUseCasesPort struct {
	ctrl     *gomock.Controller
	recorder *MockStockUseCasesPortMockRecorder
}

// MockStockUseCasesPortMockRecorder is the mock recorder for MockStockUseCasesPort.
type MockStockUseCasesPortMockRecorder struct {
	mock *MockStockUseCasesPort
}

// NewMockStockUseCasesPort creates a new mock instance.
func NewMockStockUseCasesPort(ctrl *gomock.Controller) *MockStockUseCasesPort {
	mock := &MockStockUseCasesPort{ctrl: ctrl}
	mock.recorder = &MockStockUseCasesPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockUseCasesPort) EXPECT() *MockStockUseCasesPortMockRecorder {
	return m.recorder
}

// CreateStock mocks base method.
func (m *MockStockUseCasesPort) CreateStock(ctx context.Context, s *domain0.Stock) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStock", ctx, s)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStock indicates an expected call of CreateStock.
func (mr *MockStockUseCasesPortMockRecorder) CreateStock(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStock", reflect.TypeOf((*MockStockUseCasesPort)(nil).CreateStock), ctx, s)
}

// GetLastStockByProjectID mocks base method.
func (m *MockStockUseCasesPort) GetLastStockByProjectID(ctx context.Context, projectId, supplyId int64) (*domain0.Stock, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastStockByProjectID", ctx, projectId, supplyId)
	ret0, _ := ret[0].(*domain0.Stock)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLastStockByProjectID indicates an expected call of GetLastStockByProjectID.
func (mr *MockStockUseCasesPortMockRecorder) GetLastStockByProjectID(ctx, projectId, supplyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastStockByProjectID", reflect.TypeOf((*MockStockUseCasesPort)(nil).GetLastStockByProjectID), ctx, projectId, supplyId)
}

// UpdateRealStockUnits mocks base method.
func (m *MockStockUseCasesPort) UpdateRealStockUnits(ctx context.Context, stockId int64, stock *domain0.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRealStockUnits", ctx, stockId, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRealStockUnits indicates an expected call of UpdateRealStockUnits.
func (mr *MockStockUseCasesPortMockRecorder) UpdateRealStockUnits(ctx, stockId, stock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRealStockUnits", reflect.TypeOf((*MockStockUseCasesPort)(nil).UpdateRealStockUnits), ctx, stockId, stock)
}
