// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/dashboard (interfaces: GormEngine)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockGormEngine is a mock of GormEngine interface.
type MockGormEngine struct {
	ctrl     *gomock.Controller
	recorder *MockGormEngineMockRecorder
}

// MockGormEngineMockRecorder is the mock recorder for MockGormEngine.
type MockGormEngineMockRecorder struct {
	mock *MockGormEngine
}

// NewMockGormEngine creates a new mock instance.
func NewMockGormEngine(ctrl *gomock.Controller) *MockGormEngine {
	mock := &MockGormEngine{ctrl: ctrl}
	mock.recorder = &MockGormEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGormEngine) EXPECT() *MockGormEngineMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockGormEngine) Client() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockGormEngineMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockGormEngine)(nil).Client))
}
