-- ========================================
-- MIGRATION 000070 CONSTRAINTS FKS INDEXES (DOWN)
-- ========================================
-- Nota: SQL en inglés, comentarios en español

BEGIN;

DROP INDEX IF EXISTS idx_project_dollar_values_project_id;
DROP INDEX IF EXISTS idx_lot_table_crop_commercializations_notdel;
DROP INDEX IF EXISTS idx_crop_commercializations_project_id;
DROP INDEX IF EXISTS idx_crop_commercializations_deleted_at;
DROP INDEX IF EXISTS idx_crop_commercializations_crop_id;
DROP INDEX IF EXISTS idx_lot_table_supplies_notdel;
DROP INDEX IF EXISTS idx_labor_supplies_units_v2;
DROP INDEX IF EXISTS idx_labor_supplies_notdel;
DROP INDEX IF EXISTS idx_workorder_items_workorder_id;
DROP INDEX IF EXISTS idx_workorder_items_supply_id;
DROP INDEX IF EXISTS idx_lot_table_workorder_items_notdel;
DROP INDEX IF EXISTS idx_labor_workorder_items_v2;
DROP INDEX IF EXISTS idx_labor_workorder_items_supply;
DROP INDEX IF EXISTS idx_labor_workorder_items_notdel;
DROP INDEX IF EXISTS idx_lot_table_workorders_notdel;
DROP INDEX IF EXISTS idx_lot_table_workorders_composite;
DROP INDEX IF EXISTS idx_labor_workorders_metrics_v2;
DROP INDEX IF EXISTS idx_labor_workorders_metrics_notdel;
DROP INDEX IF EXISTS idx_labor_workorders_composite;
DROP INDEX IF EXISTS idx_labor_grouping;
DROP INDEX IF EXISTS idx_lot_table_labors_sowing;
DROP INDEX IF EXISTS idx_lot_table_labors_notdel;
DROP INDEX IF EXISTS idx_lot_table_labors_harvest;
DROP INDEX IF EXISTS idx_labors_project_id;
DROP INDEX IF EXISTS idx_labors_category_id;
DROP INDEX IF EXISTS idx_labor_labors_notdel;
DROP INDEX IF EXISTS idx_lot_table_crops_notdel;
DROP INDEX IF EXISTS idx_lots_previous_crop_id;
DROP INDEX IF EXISTS idx_lots_field_id;
DROP INDEX IF EXISTS idx_lots_current_crop_id;
DROP INDEX IF EXISTS idx_lot_table_lots_notdel;
DROP INDEX IF EXISTS idx_lot_table_lots_composite;
DROP INDEX IF EXISTS idx_lot_table_fields_notdel;
DROP INDEX IF EXISTS idx_fields_project_id;
DROP INDEX IF EXISTS idx_projects_id;
DROP INDEX IF EXISTS idx_projects_customer_id;
DROP INDEX IF EXISTS idx_projects_campaign_id;
DROP INDEX IF EXISTS idx_lot_table_projects_notdel;
DROP INDEX IF EXISTS idx_fx_rates_effective_date;
DROP INDEX IF EXISTS idx_business_parameters_key;
DROP INDEX IF EXISTS idx_business_parameters_category;
DROP INDEX IF EXISTS idx_users_deleted_at;
ALTER TABLE ONLY public.invoices DROP CONSTRAINT IF EXISTS fk_invoices_work_order;
ALTER TABLE ONLY public.project_dollar_values DROP CONSTRAINT IF EXISTS fk_project;
ALTER TABLE ONLY public.field_investors DROP CONSTRAINT IF EXISTS fk_field_investors_investor;
ALTER TABLE ONLY public.field_investors DROP CONSTRAINT IF EXISTS fk_field_investors_field;
ALTER TABLE ONLY public.admin_cost_investors DROP CONSTRAINT IF EXISTS fk_admin_cost_investors_project;
ALTER TABLE ONLY public.admin_cost_investors DROP CONSTRAINT IF EXISTS fk_admin_cost_investors_investor;
ALTER TABLE ONLY public.crop_commercializations DROP CONSTRAINT IF EXISTS fk_project;
ALTER TABLE ONLY public.crop_commercializations DROP CONSTRAINT IF EXISTS fk_crop;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_updated_by;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_project;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_investor;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_deleted_by;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS fk_project_investors_created_by;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS fk_investors_updated_by;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS fk_investors_deleted_by;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS fk_investors_created_by;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS fk_supply;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS fk_provider;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS fk_investor;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS fk_supply;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS fk_project;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS fk_investor;
ALTER TABLE ONLY public.supplies DROP CONSTRAINT IF EXISTS fk_type;
ALTER TABLE ONLY public.supplies DROP CONSTRAINT IF EXISTS fk_category;
ALTER TABLE ONLY public.categories DROP CONSTRAINT IF EXISTS categories_type_id_fkey;
ALTER TABLE ONLY public.workorder_items DROP CONSTRAINT IF EXISTS workorder_items_workorder_id_fkey;
ALTER TABLE ONLY public.workorder_items DROP CONSTRAINT IF EXISTS workorder_items_supply_id_fkey;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS workorders_project_id_fkey;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS workorders_lot_id_fkey;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS workorders_labor_id_fkey;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS workorders_field_id_fkey;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS workorders_crop_id_fkey;
ALTER TABLE ONLY public.labors DROP CONSTRAINT IF EXISTS fk_project;
ALTER TABLE ONLY public.labors DROP CONSTRAINT IF EXISTS fk_category;
ALTER TABLE ONLY public.labor_categories DROP CONSTRAINT IF EXISTS labor_categories_type_id_fkey;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS fk_crops_updated_by;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS fk_crops_deleted_by;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS fk_crops_created_by;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_updated_by;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_previous_crop;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_field;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_deleted_by;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_current_crop;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS fk_lots_created_by;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_lease_type;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_updated_by;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_project;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_deleted_by;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fk_fields_created_by;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS fk_lease_types_updated_by;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS fk_lease_types_deleted_by;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS fk_lease_types_created_by;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_updated_by;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_project;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_manager;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_deleted_by;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS fk_project_managers_created_by;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS fk_managers_updated_by;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS fk_managers_deleted_by;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS fk_managers_created_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_updated_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_deleted_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_customer;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_created_by;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS fk_projects_campaign;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS fk_campaigns_updated_by;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS fk_campaigns_deleted_by;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS fk_campaigns_created_by;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS fk_customers_updated_by;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS fk_customers_deleted_by;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS fk_customers_created_by;
ALTER TABLE ONLY public.invoices DROP CONSTRAINT IF EXISTS invoices_work_order_id_key;
ALTER TABLE ONLY public.invoices DROP CONSTRAINT IF EXISTS invoices_pkey;
ALTER TABLE ONLY public.project_dollar_values DROP CONSTRAINT IF EXISTS project_dollar_values_project_id_year_month_key;
ALTER TABLE ONLY public.project_dollar_values DROP CONSTRAINT IF EXISTS project_dollar_values_pkey;
ALTER TABLE ONLY public.field_investors DROP CONSTRAINT IF EXISTS field_investors_pkey;
ALTER TABLE ONLY public.admin_cost_investors DROP CONSTRAINT IF EXISTS admin_cost_investors_pkey;
ALTER TABLE ONLY public.crop_commercializations DROP CONSTRAINT IF EXISTS crop_commercializations_pkey;
ALTER TABLE ONLY public.project_investors DROP CONSTRAINT IF EXISTS project_investors_pkey;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS investors_pkey;
ALTER TABLE ONLY public.investors DROP CONSTRAINT IF EXISTS investors_name_key;
ALTER TABLE ONLY public.providers DROP CONSTRAINT IF EXISTS providers_pkey;
ALTER TABLE ONLY public.providers DROP CONSTRAINT IF EXISTS providers_name_key;
ALTER TABLE ONLY public.supply_movements DROP CONSTRAINT IF EXISTS supply_movements_pkey;
ALTER TABLE ONLY public.stocks DROP CONSTRAINT IF EXISTS stocks_pkey;
ALTER TABLE ONLY public.supplies DROP CONSTRAINT IF EXISTS supplies_pkey;
ALTER TABLE ONLY public.categories DROP CONSTRAINT IF EXISTS categories_pkey;
ALTER TABLE ONLY public.types DROP CONSTRAINT IF EXISTS types_pkey;
ALTER TABLE ONLY public.types DROP CONSTRAINT IF EXISTS types_name_key;
ALTER TABLE ONLY public.workorder_items DROP CONSTRAINT IF EXISTS workorder_items_pkey;
ALTER TABLE ONLY public.workorders DROP CONSTRAINT IF EXISTS workorders_pkey;
ALTER TABLE ONLY public.labors DROP CONSTRAINT IF EXISTS labors_pkey;
ALTER TABLE ONLY public.labor_categories DROP CONSTRAINT IF EXISTS labor_categories_pkey;
ALTER TABLE ONLY public.labor_types DROP CONSTRAINT IF EXISTS labor_types_pkey;
ALTER TABLE ONLY public.labor_types DROP CONSTRAINT IF EXISTS labor_types_name_key;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS crops_pkey;
ALTER TABLE ONLY public.crops DROP CONSTRAINT IF EXISTS crops_name_key;
ALTER TABLE ONLY public.lots DROP CONSTRAINT IF EXISTS lots_pkey;
ALTER TABLE ONLY public.fields DROP CONSTRAINT IF EXISTS fields_pkey;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS lease_types_pkey;
ALTER TABLE ONLY public.lease_types DROP CONSTRAINT IF EXISTS lease_types_name_key;
ALTER TABLE ONLY public.project_managers DROP CONSTRAINT IF EXISTS project_managers_pkey;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS managers_pkey;
ALTER TABLE ONLY public.managers DROP CONSTRAINT IF EXISTS managers_name_key;
ALTER TABLE ONLY public.projects DROP CONSTRAINT IF EXISTS projects_pkey;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS campaigns_pkey;
ALTER TABLE ONLY public.campaigns DROP CONSTRAINT IF EXISTS campaigns_name_key;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS customers_pkey;
ALTER TABLE ONLY public.customers DROP CONSTRAINT IF EXISTS customers_name_key;
ALTER TABLE ONLY public.fx_rates DROP CONSTRAINT IF EXISTS fx_rates_pkey;
ALTER TABLE ONLY public.business_parameters DROP CONSTRAINT IF EXISTS business_parameters_pkey;
ALTER TABLE ONLY public.business_parameters DROP CONSTRAINT IF EXISTS business_parameters_key_key;
ALTER TABLE ONLY public.users DROP CONSTRAINT IF EXISTS users_username_key;
ALTER TABLE ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE ONLY public.users DROP CONSTRAINT IF EXISTS uni_users_username;

COMMIT;
