services:
  ponti-api:
    build:
      context: ../../
      dockerfile: ./projects/ponti-api/Dockerfile.stg
    image: "ponti-api:${APP_VERSION}"
    env_file:
      - .env
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    environment:
      - DEPLOY_ENV=${DEPLOY_ENV}
      - APP_ROOT=/app
      - GO111MODULE=on
      - GIN_MODE=debug
    depends_on:
      ponti-db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    user: "1000:1000"
    command: ["/app/stg_binary"]

  ponti-db:
    image: postgres:16.3
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ponti-db_data:/var/lib/postgresql/data
      - ./infra/postgres-storage:/storage
      - ./infra/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    depends_on:
      ponti-db:
        condition: service_healthy
    volumes:
      - ./projects/ponti-api/migrations:/migrations
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}",
      "force", "3"
    ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ponti-db_data:
