name: Build, Push to Artifact Registry, and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: pontisoft
  GCP_REGION: us-central1
  REPOSITORY_NAME: ui-registry
  SERVICE_NAME: ui
  IMAGE_NAME: ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar credenciales de Google Cloud
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > key.json

      - name: Autenticar Docker para Artifact Registry
        run: |
          cat key.json | docker login -u _json_key --password-stdin https://${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Autenticar en gcloud
        run: |
          gcloud auth activate-service-account --key-file=key.json

      - name: Build, tag, and push image to Artifact Registry
        id: build-image
        run: |
          # Usar los primeros 7 caracteres del SHA del commit como versión
          IMAGE_TAG=${GITHUB_SHA::7}

          FULL_IMAGE_NAME=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG

          docker build -t $FULL_IMAGE_NAME .
          docker push $FULL_IMAGE_NAME
          echo "image=$FULL_IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ steps.build-image.outputs.image }} \
            --platform=managed \
            --region=${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --quiet

      - name: Limpiar archivos de credenciales
        if: always()
        run: |
          rm -f key.json
