package lot

import (
	"context"
	"errors"
	"fmt"

	gorm "gorm.io/gorm"

	types "github.com/alphacodinggroup/ponti-backend/pkg/types"

	models "github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/lot/repository/models"
	domain "github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/lot/usecases/domain"
)

type GormEnginePort interface {
	Client() *gorm.DB
}
type Repository struct {
	db GormEnginePort
}

func NewRepository(db GormEnginePort) *Repository {
	return &Repository{
		db: db,
	}
}

// CreateLot persists a Lot and returns its autogenerated ID.
func (r *Repository) CreateLot(ctx context.Context, l *domain.Lot) (int64, error) {
	if l == nil {
		return 0, types.NewError(types.ErrValidation, "lot is nil", nil)
	}
	model := models.FromDomain(l)
	if err := r.db.Client().WithContext(ctx).Create(model).Error; err != nil {
		return 0, types.NewError(types.ErrInternal, "failed to create lot", err)
	}
	return model.ID, nil
}

// ListLots returns all lots.
func (r *Repository) ListLots(ctx context.Context, fieldID int64) ([]domain.Lot, error) {
	var list []models.Lot
	if err := r.db.Client().WithContext(ctx).Where("field_id = ?", fieldID).Find(&list).Error; err != nil {
		return nil, types.NewError(types.ErrInternal, "failed to list lots", err)
	}
	result := make([]domain.Lot, 0, len(list))
	for _, m := range list {
		result = append(result, *m.ToDomain())
	}
	return result, nil
}

// GetLot retrieves a lot by its ID.
func (r *Repository) GetLot(ctx context.Context, id int64) (*domain.Lot, error) {
	var model models.Lot
	err := r.db.Client().WithContext(ctx).Where("id = ?", id).First(&model).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, types.NewError(types.ErrNotFound, fmt.Sprintf("lot with id %d not found", id), err)
		}
		return nil, types.NewError(types.ErrInternal, "failed to get lot", err)
	}
	return model.ToDomain(), nil
}

// UpdateLot updates an existing lot.
func (r *Repository) UpdateLot(ctx context.Context, l *domain.Lot) error {
	if l == nil {
		return types.NewError(types.ErrValidation, "lot is nil", nil)
	}
	result := r.db.Client().WithContext(ctx).
		Model(&models.Lot{}).
		Where("id = ?", l.ID).
		Updates(models.FromDomain(l))
	if result.Error != nil {
		return types.NewError(types.ErrInternal, "failed to update lot", result.Error)
	}
	if result.RowsAffected == 0 {
		return types.NewError(types.ErrNotFound, fmt.Sprintf("lot with id %d does not exist", l.ID), nil)
	}
	return nil
}

// DeleteLot deletes a lot by its ID.
func (r *Repository) DeleteLot(ctx context.Context, id int64) error {
	result := r.db.Client().WithContext(ctx).
		Delete(&models.Lot{}, "id = ?", id)
	if result.Error != nil {
		return types.NewError(types.ErrInternal, "failed to delete lot", result.Error)
	}
	if result.RowsAffected == 0 {
		return types.NewError(types.ErrNotFound, fmt.Sprintf("lot with id %d does not exist", id), nil)
	}
	return nil
}
