// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/alphacodinggroup/ponti-backend/pkg/databases/sql/gorm"
	"github.com/alphacodinggroup/ponti-backend/pkg/http/middlewares/gin"
	"github.com/alphacodinggroup/ponti-backend/pkg/http/servers/gin"
	"github.com/alphacodinggroup/ponti-backend/pkg/words-suggesters/trigram-search"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/cmd/config"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/campaign"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/crop"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/customer"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/field"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/investor"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/lot"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/manager"
	"github.com/alphacodinggroup/ponti-backend/projects/ponti-api/internal/project"
)

// Injectors from wire.go:

func Initialize() (*Dependencies, error) {
	allConfigs, err := ProvideAllConfigs()
	if err != nil {
		return nil, err
	}
	server, err := ProvideGinEngine(allConfigs)
	if err != nil {
		return nil, err
	}
	db := ProvideConfigDB(allConfigs)
	repository, err := ProvideGormRepository(db)
	if err != nil {
		return nil, err
	}
	middlewares := ProvideMiddlewares()
	pkgsuggesterDB := ProvideSuggesterDB(repository)
	wordsSuggester := ProvideConfigSuggester(allConfigs)
	pkgsuggesterWordsSuggester, err := ProvideSuggester(pkgsuggesterDB, wordsSuggester)
	if err != nil {
		return nil, err
	}
	ginEnginePort := ProvideCustomerGinEnginePort(server)
	gormEnginePort := ProvideCustomerGormEnginePort(repository)
	customerRepository := ProvideCustomerRepository(gormEnginePort)
	repositoryPort := ProvideCustomerRepositoryPort(customerRepository)
	useCases := ProvideCustomerUseCases(repositoryPort)
	useCasesPort := ProvideCustomerUseCasesPort(useCases)
	configAPIPort := ProvideCustomerConfigAPI(allConfigs)
	middlewaresEnginePort := ProvideCustomerMiddlewaresEnginePort(middlewares)
	handler := ProvideCustomerHandler(ginEnginePort, useCasesPort, configAPIPort, middlewaresEnginePort)
	campaignGinEnginePort := ProvideCampaignGinEnginePort(server)
	campaignGormEnginePort := ProvideCampaignGormEnginePort(repository)
	campaignRepository := ProvideCampaignRepository(campaignGormEnginePort)
	campaignRepositoryPort := ProvideCampaignRepositoryPort(campaignRepository)
	campaignUseCases := ProvideCampaignUseCases(campaignRepositoryPort)
	campaignUseCasesPort := ProvideCampaignUseCasesPort(campaignUseCases)
	campaignConfigAPIPort := ProvideCampaignConfigAPI(allConfigs)
	campaignMiddlewaresEnginePort := ProvideCampaignMiddlewaresEnginePort(middlewares)
	campaignHandler := ProvideCampaignHandler(campaignGinEnginePort, campaignUseCasesPort, campaignConfigAPIPort, campaignMiddlewaresEnginePort)
	investorGinEnginePort := ProvideInvestorGinEnginePort(server)
	investorGormEnginePort := ProvideInvestorGormEnginePort(repository)
	investorRepository := ProvideInvestorRepository(investorGormEnginePort)
	investorRepositoryPort := ProvideInvestorRepositoryPort(investorRepository)
	investorUseCases := ProvideInvestorUseCases(investorRepositoryPort)
	investorUseCasesPort := ProvideInvestorUseCasesPort(investorUseCases)
	investorConfigAPIPort := ProvideInvestorConfigAPI(allConfigs)
	investorMiddlewaresEnginePort := ProvideInvestorMiddlewaresEnginePort(middlewares)
	investorHandler := ProvideInvestorHandler(investorGinEnginePort, investorUseCasesPort, investorConfigAPIPort, investorMiddlewaresEnginePort)
	cropGinEnginePort := ProvideCropGinEnginePort(server)
	cropGormEnginePort := ProvideCropGormEnginePort(repository)
	cropRepository := ProvideCropRepository(cropGormEnginePort)
	cropRepositoryPort := ProvideCropRepositoryPort(cropRepository)
	cropUseCases := ProvideCropUseCases(cropRepositoryPort)
	cropUseCasesPort := ProvideCropUseCasesPort(cropUseCases)
	cropConfigAPIPort := ProvideCropConfigAPI(allConfigs)
	cropMiddlewaresEnginePort := ProvideCropMiddlewaresEnginePort(middlewares)
	cropHandler := ProvideCropHandler(cropGinEnginePort, cropUseCasesPort, cropConfigAPIPort, cropMiddlewaresEnginePort)
	lotGinEnginePort := ProvideLotGinEnginePort(server)
	lotGormEnginePort := ProvideLotGormEnginePort(repository)
	lotRepository := ProvideLotRepository(lotGormEnginePort)
	lotRepositoryPort := ProvideLotRepositoryPort(lotRepository)
	lotUseCases := ProvideLotUseCases(lotRepositoryPort, cropUseCasesPort)
	lotUseCasesPort := ProvideLotUseCasesPort(lotUseCases)
	lotConfigAPIPort := ProvideLotConfigAPI(allConfigs)
	lotMiddlewaresEnginePort := ProvideLotMiddlewaresEnginePort(middlewares)
	lotHandler := ProvideLotHandler(lotGinEnginePort, lotUseCasesPort, lotConfigAPIPort, lotMiddlewaresEnginePort)
	fieldGinEnginePort := ProvideFieldGinEnginePort(server)
	fieldGormEnginePort := ProvideFieldGormEnginePort(repository)
	fieldRepository := ProvideFieldRepository(fieldGormEnginePort)
	fieldRepositoryPort := ProvideFieldRepositoryPort(fieldRepository)
	fieldUseCases := ProvideFieldUseCases(fieldRepositoryPort, lotUseCasesPort)
	fieldUseCasesPort := ProvideFieldUseCasesPort(fieldUseCases)
	fieldConfigAPIPort := ProvideFieldConfigAPI(allConfigs)
	fieldMiddlewaresEnginePort := ProvideFieldMiddlewaresEnginePort(middlewares)
	fieldHandler := ProvideFieldHandler(fieldGinEnginePort, fieldUseCasesPort, fieldConfigAPIPort, fieldMiddlewaresEnginePort)
	managerGinEnginePort := ProvideManagerGinEnginePort(server)
	managerGormEnginePort := ProvideManagerGormEnginePort(repository)
	managerRepository := ProvideManagerRepository(managerGormEnginePort)
	managerRepositoryPort := ProvideManagerRepositoryPort(managerRepository)
	managerUseCases := ProvideManagerUseCases(managerRepositoryPort)
	managerUseCasesPort := ProvideManagerUseCasesPort(managerUseCases)
	managerConfigAPIPort := ProvideManagerConfigAPI(allConfigs)
	managerMiddlewaresEnginePort := ProvideManagerMiddlewaresEnginePort(middlewares)
	managerHandler := ProvideManagerHandler(managerGinEnginePort, managerUseCasesPort, managerConfigAPIPort, managerMiddlewaresEnginePort)
	projectGinEnginePort := ProvideProjectGinEnginePort(server)
	projectGormEnginePort := ProvideProjectGormEnginePort(repository)
	projectRepository := ProvideProjectRepository(projectGormEnginePort)
	projectRepositoryPort := ProvideProjectRepositoryPort(projectRepository)
	wordsSuggesterPort := ProvideProjectSuggesterPort(pkgsuggesterWordsSuggester)
	projectUseCases := ProvideProjectUseCases(projectRepositoryPort, wordsSuggesterPort, useCasesPort, campaignUseCasesPort, managerUseCasesPort, investorUseCasesPort, fieldUseCasesPort)
	projectUseCasesPort := ProvideProjectUseCasesPort(projectUseCases)
	projectConfigAPIPort := ProvideProjectConfigAPI(allConfigs)
	projectMiddlewaresEnginePort := ProvideProjectMiddlewaresEnginePort(middlewares)
	projectHandler := ProvideProjectHandler(projectGinEnginePort, projectUseCasesPort, projectConfigAPIPort, projectMiddlewaresEnginePort)
	dependencies := &Dependencies{
		Config:          allConfigs,
		GinEngine:       server,
		GormRepo:        repository,
		Middlewares:     middlewares,
		WordsSuggester:  pkgsuggesterWordsSuggester,
		CustomerHandler: handler,
		CampaignHandler: campaignHandler,
		InvestorHandler: investorHandler,
		CropHandler:     cropHandler,
		LotHandler:      lotHandler,
		FieldHandler:    fieldHandler,
		ManagerHandler:  managerHandler,
		ProjectHandler:  projectHandler,
	}
	return dependencies, nil
}

// wire.go:

type Dependencies struct {
	Config          *config.AllConfigs
	GinEngine       *pkggin.Server
	GormRepo        *pkggorm.Repository
	Middlewares     *pkgmwr.Middlewares
	WordsSuggester  *pkgsuggester.WordsSuggester
	CustomerHandler *customer.Handler
	CampaignHandler *campaign.Handler
	InvestorHandler *investor.Handler
	CropHandler     *crop.Handler
	LotHandler      *lot.Handler
	FieldHandler    *field.Handler
	ManagerHandler  *manager.Handler
	ProjectHandler  *project.Handler
}
