// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/alphacodinggroup/ponti-backend/cmd/config"
	"github.com/alphacodinggroup/ponti-backend/internal/ai"
	"github.com/alphacodinggroup/ponti-backend/internal/business-parameters"
	"github.com/alphacodinggroup/ponti-backend/internal/campaign"
	"github.com/alphacodinggroup/ponti-backend/internal/category"
	"github.com/alphacodinggroup/ponti-backend/internal/class-type"
	"github.com/alphacodinggroup/ponti-backend/internal/commercialization"
	"github.com/alphacodinggroup/ponti-backend/internal/crop"
	"github.com/alphacodinggroup/ponti-backend/internal/customer"
	"github.com/alphacodinggroup/ponti-backend/internal/dashboard"
	"github.com/alphacodinggroup/ponti-backend/internal/data-integrity"
	"github.com/alphacodinggroup/ponti-backend/internal/dollar"
	"github.com/alphacodinggroup/ponti-backend/internal/field"
	"github.com/alphacodinggroup/ponti-backend/internal/investor"
	"github.com/alphacodinggroup/ponti-backend/internal/invoice"
	"github.com/alphacodinggroup/ponti-backend/internal/labor"
	"github.com/alphacodinggroup/ponti-backend/internal/lease-type"
	"github.com/alphacodinggroup/ponti-backend/internal/lot"
	"github.com/alphacodinggroup/ponti-backend/internal/manager"
	"github.com/alphacodinggroup/ponti-backend/internal/project"
	"github.com/alphacodinggroup/ponti-backend/internal/provider"
	"github.com/alphacodinggroup/ponti-backend/internal/report"
	"github.com/alphacodinggroup/ponti-backend/internal/stock"
	"github.com/alphacodinggroup/ponti-backend/internal/supply"
	"github.com/alphacodinggroup/ponti-backend/internal/work-order"
	"github.com/alphacodinggroup/ponti-backend/pkg/databases/sql/gorm"
	"github.com/alphacodinggroup/ponti-backend/pkg/http/middlewares/gin"
	"github.com/alphacodinggroup/ponti-backend/pkg/http/servers/gin"
	"github.com/alphacodinggroup/ponti-backend/pkg/words-suggesters/trigram-search"
)

// Injectors from wire.go:

func Initialize() (*Dependencies, error) {
	config, err := ProvideAllConfigs()
	if err != nil {
		return nil, err
	}
	server, err := ProvideGinEngine(config)
	if err != nil {
		return nil, err
	}
	db := ProvideConfigDB(config)
	repository, err := ProvideGormRepository(db)
	if err != nil {
		return nil, err
	}
	middlewares := ProvideMiddlewares()
	pkgsuggesterDB := ProvideSuggesterDB(repository)
	wordsSuggester := ProvideConfigSuggester(config)
	pkgsuggesterWordsSuggester, err := ProvideSuggester(pkgsuggesterDB, wordsSuggester)
	if err != nil {
		return nil, err
	}
	ginEnginePort := ProvideCustomerGinEnginePort(server)
	gormEnginePort := ProvideCustomerGormEnginePort(repository)
	customerRepository := ProvideCustomerRepository(gormEnginePort)
	repositoryPort := ProvideCustomerRepositoryPort(customerRepository)
	useCases := ProvideCustomerUseCases(repositoryPort)
	useCasesPort := ProvideCustomerUseCasesPort(useCases)
	configAPIPort := ProvideCustomerConfigAPI(config)
	middlewaresEnginePort := ProvideCustomerMiddlewaresEnginePort(middlewares)
	handler := ProvideCustomerHandler(ginEnginePort, useCasesPort, configAPIPort, middlewaresEnginePort)
	campaignGinEnginePort := ProvideCampaignGinEnginePort(server)
	campaignGormEnginePort := ProvideCampaignGormEnginePort(repository)
	campaignRepository := ProvideCampaignRepository(campaignGormEnginePort)
	campaignRepositoryPort := ProvideCampaignRepositoryPort(campaignRepository)
	campaignUseCases := ProvideCampaignUseCases(campaignRepositoryPort)
	campaignUseCasesPort := ProvideCampaignUseCasesPort(campaignUseCases)
	campaignConfigAPIPort := ProvideCampaignConfigAPI(config)
	campaignMiddlewaresEnginePort := ProvideCampaignMiddlewaresEnginePort(middlewares)
	campaignHandler := ProvideCampaignHandler(campaignGinEnginePort, campaignUseCasesPort, campaignConfigAPIPort, campaignMiddlewaresEnginePort)
	dashboardGinEnginePort := ProvideDashboardGinEnginePort(server)
	dashboardGormEnginePort := ProvideDashboardGormEnginePort(repository)
	dashboardRepository := ProvideDashboardRepository(dashboardGormEnginePort)
	dashboardRepositoryPort := ProvideDashboardRepositoryPort(dashboardRepository)
	dashboardUseCases := ProvideDashboardUseCases(dashboardRepositoryPort)
	dashboardUseCasesPort := ProvideDashboardUseCasesPort(dashboardUseCases)
	dashboardConfigAPIPort := ProvideDashboardConfigAPI(config)
	dashboardMiddlewaresEnginePort := ProvideDashboardMiddlewaresEnginePort(middlewares)
	dashboardHandler := ProvideDashboardHandler(dashboardGinEnginePort, dashboardUseCasesPort, dashboardConfigAPIPort, dashboardMiddlewaresEnginePort)
	dataintegrityGinEnginePort := ProvideDataIntegrityGinEnginePort(server)
	gormEngine := ProvideWorkOrderGormEnginePort(repository)
	workorderRepository := ProvideWorkOrderRepository(gormEngine)
	workorderRepositoryPort := ProvideWorkOrderRepositoryPort(workorderRepository)
	workOrderRepositoryPort := ProvideDataIntegrityWorkOrderRepositoryPort(workorderRepositoryPort)
	dataintegrityDashboardRepositoryPort := ProvideDataIntegrityDashboardRepositoryPort(dashboardRepositoryPort)
	lotGormEnginePort := ProvideLotGormEnginePort(repository)
	lotRepository := ProvideLotRepository(lotGormEnginePort)
	lotRepositoryPort := ProvideLotRepositoryPort(lotRepository)
	dataintegrityLotRepositoryPort := ProvideDataIntegrityLotRepositoryPort(lotRepositoryPort)
	reportGormEnginePort := ProvideReportGormEnginePort(repository)
	reportRepository := ProvideReportRepository(reportGormEnginePort)
	reportRepositoryPort := ProvideReportRepositoryPort(reportRepository)
	dataintegrityReportRepositoryPort := ProvideDataIntegrityReportRepositoryPort(reportRepositoryPort)
	stockGormEnginePort := ProvideStockGormEnginePort(repository)
	stockRepository := ProvideStockRepository(stockGormEnginePort)
	stockRepositoryPort := ProvideStockRepositoryPort(stockRepository)
	dataintegrityStockRepositoryPort := ProvideDataIntegrityStockRepositoryPort(stockRepositoryPort)
	dataintegrityUseCases := ProvideDataIntegrityUseCases(workOrderRepositoryPort, dataintegrityDashboardRepositoryPort, dataintegrityLotRepositoryPort, dataintegrityReportRepositoryPort, dataintegrityStockRepositoryPort)
	dataintegrityUseCasesPort := ProvideDataIntegrityUseCasesPort(dataintegrityUseCases)
	dataintegrityConfigAPIPort := ProvideDataIntegrityConfigAPI(config)
	dataintegrityMiddlewaresEnginePort := ProvideDataIntegrityMiddlewaresEnginePort(middlewares)
	dataintegrityHandler := ProvideDataIntegrityHandler(dataintegrityGinEnginePort, dataintegrityUseCasesPort, dataintegrityConfigAPIPort, dataintegrityMiddlewaresEnginePort)
	investorGinEnginePort := ProvideInvestorGinEnginePort(server)
	investorGormEnginePort := ProvideInvestorGormEnginePort(repository)
	investorRepository := ProvideInvestorRepository(investorGormEnginePort)
	investorRepositoryPort := ProvideInvestorRepositoryPort(investorRepository)
	investorUseCases := ProvideInvestorUseCases(investorRepositoryPort)
	investorUseCasesPort := ProvideInvestorUseCasesPort(investorUseCases)
	investorConfigAPIPort := ProvideInvestorConfigAPI(config)
	investorMiddlewaresEnginePort := ProvideInvestorMiddlewaresEnginePort(middlewares)
	investorHandler := ProvideInvestorHandler(investorGinEnginePort, investorUseCasesPort, investorConfigAPIPort, investorMiddlewaresEnginePort)
	cropGinEnginePort := ProvideCropGinEnginePort(server)
	cropGormEnginePort := ProvideCropGormEnginePort(repository)
	cropRepository := ProvideCropRepository(cropGormEnginePort)
	cropRepositoryPort := ProvideCropRepositoryPort(cropRepository)
	cropUseCases := ProvideCropUseCases(cropRepositoryPort)
	cropUseCasesPort := ProvideCropUseCasesPort(cropUseCases)
	cropConfigAPIPort := ProvideCropConfigAPI(config)
	cropMiddlewaresEnginePort := ProvideCropMiddlewaresEnginePort(middlewares)
	cropHandler := ProvideCropHandler(cropGinEnginePort, cropUseCasesPort, cropConfigAPIPort, cropMiddlewaresEnginePort)
	lotGinEnginePort := ProvideLotGinEnginePort(server)
	lotExcelService, err := ProvideLotPkgExcelService()
	if err != nil {
		return nil, err
	}
	xlsxEnginePort := ProvideLotXLSXEnginePort(lotExcelService)
	exporterAdapterPort := ProvideLotExporterPort(xlsxEnginePort)
	lotUseCases := ProvideLotUseCases(lotRepositoryPort, exporterAdapterPort)
	lotUseCasesPort := ProvideLotUseCasesPort(lotUseCases)
	lotConfigAPIPort := ProvideLotConfigAPI(config)
	lotMiddlewaresEnginePort := ProvideLotMiddlewaresEnginePort(middlewares)
	lotHandler := ProvideLotHandler(lotGinEnginePort, lotUseCasesPort, lotConfigAPIPort, lotMiddlewaresEnginePort)
	fieldGinEnginePort := ProvideFieldGinEnginePort(server)
	fieldGormEnginePort := ProvideFieldGormEnginePort(repository)
	fieldRepository := ProvideFieldRepository(fieldGormEnginePort)
	fieldRepositoryPort := ProvideFieldRepositoryPort(fieldRepository)
	fieldUseCases := ProvideFieldUseCases(fieldRepositoryPort)
	fieldUseCasesPort := ProvideFieldUseCasesPort(fieldUseCases)
	fieldConfigAPIPort := ProvideFieldConfigAPI(config)
	fieldMiddlewaresEnginePort := ProvideFieldMiddlewaresEnginePort(middlewares)
	fieldHandler := ProvideFieldHandler(fieldGinEnginePort, fieldUseCasesPort, fieldConfigAPIPort, fieldMiddlewaresEnginePort)
	managerGinEnginePort := ProvideManagerGinEnginePort(server)
	managerGormEnginePort := ProvideManagerGormEnginePort(repository)
	managerRepository := ProvideManagerRepository(managerGormEnginePort)
	managerRepositoryPort := ProvideManagerRepositoryPort(managerRepository)
	managerUseCases := ProvideManagerUseCases(managerRepositoryPort)
	managerUseCasesPort := ProvideManagerUseCasesPort(managerUseCases)
	managerConfigAPIPort := ProvideManagerConfigAPI(config)
	managerMiddlewaresEnginePort := ProvideManagerMiddlewaresEnginePort(middlewares)
	managerHandler := ProvideManagerHandler(managerGinEnginePort, managerUseCasesPort, managerConfigAPIPort, managerMiddlewaresEnginePort)
	projectGinEnginePort := ProvideProjectGinEnginePort(server)
	projectGormEnginePort := ProvideProjectGormEnginePort(repository)
	projectRepository := ProvideProjectRepository(projectGormEnginePort)
	projectRepositoryPort := ProvideProjectRepositoryPort(projectRepository)
	wordsSuggesterPort := ProvideProjectSuggesterPort(pkgsuggesterWordsSuggester)
	projectUseCases := ProvideProjectUseCases(projectRepositoryPort, wordsSuggesterPort)
	projectUseCasesPort := ProvideProjectUseCasesPort(projectUseCases)
	projectConfigAPIPort := ProvideProjectConfigAPI(config)
	projectMiddlewaresEnginePort := ProvideProjectMiddlewaresEnginePort(middlewares)
	projectHandler := ProvideProjectHandler(projectGinEnginePort, projectUseCasesPort, projectConfigAPIPort, projectMiddlewaresEnginePort)
	providerGinEnginePort := ProvideProviderGinEnginePort(server)
	providerGormEnginePort := ProvideProviderGormEnginePort(repository)
	providerRepository := ProvideProviderRepository(providerGormEnginePort)
	providerRepositoryPort := ProvideProviderRepositoryPort(providerRepository)
	providerUseCases := ProvideProviderUseCases(providerRepositoryPort)
	providerUseCasesPort := ProvideProviderUseCasesPort(providerUseCases)
	providerConfigAPIPort := ProvideProviderConfigAPI(config)
	providerMiddlewaresEnginePort := ProvideProviderMiddlewaresEnginePort(middlewares)
	providerHandler := ProvideProviderHandler(providerGinEnginePort, providerUseCasesPort, providerConfigAPIPort, providerMiddlewaresEnginePort)
	reportGinEnginePort := ProvideReportGinEnginePort(server)
	reportUseCase := ProvideReportUseCases(reportRepositoryPort)
	reportUseCasePort := ProvideReportUseCasesPort(reportUseCase)
	reportConfigAPIPort := ProvideReportConfigAPI(config)
	reportMiddlewaresEnginePort := ProvideReportMiddlewaresEnginePort(middlewares)
	reportHandler := ProvideReportHandler(reportGinEnginePort, reportUseCasePort, reportConfigAPIPort, reportMiddlewaresEnginePort)
	leasetypeGinEnginePort := ProvideLeaseTypeGinEnginePort(server)
	leasetypeGormEnginePort := ProvideLeaseTypeGormEnginePort(repository)
	leasetypeRepository := ProvideLeaseTypeRepository(leasetypeGormEnginePort)
	leasetypeRepositoryPort := ProvideLeaseTypeRepositoryPort(leasetypeRepository)
	leasetypeUseCases := ProvideLeaseTypeUseCases(leasetypeRepositoryPort)
	leasetypeUseCasesPort := ProvideLeaseTypeUseCasesPort(leasetypeUseCases)
	leasetypeConfigAPIPort := ProvideLeaseTypeConfigAPI(config)
	leasetypeMiddlewaresEnginePort := ProvideLeaseTypeMiddlewaresEnginePort(middlewares)
	leasetypeHandler := ProvideLeaseTypeHandler(leasetypeGinEnginePort, leasetypeUseCasesPort, leasetypeConfigAPIPort, leasetypeMiddlewaresEnginePort)
	supplyGinEnginePort := ProvideSupplyGinEnginePort(server)
	supplyGormEnginePort := ProvideSupplyGormEnginePort(repository)
	supplyRepository := ProvideSupplyRepository(supplyGormEnginePort)
	supplyRepositoryPort := ProvideSupplyRepositoryPort(supplyRepository)
	supplyExcelService, err := ProvideSupplyPkgExcelService()
	if err != nil {
		return nil, err
	}
	supplyXLSXEnginePort := ProvideSupplyXLSXEnginePort(supplyExcelService)
	supplyExporterAdapterPort := ProvideSupplyExporterPort(supplyXLSXEnginePort)
	stockExcelService, err := ProvideStockPkgExcelService()
	if err != nil {
		return nil, err
	}
	stockXLSXEnginePort := ProvideStockXLSXEnginePort(stockExcelService)
	stockExporterAdapterPort := ProvideStockExporterPort(stockXLSXEnginePort)
	stockUseCases := ProvideStockUseCases(stockRepositoryPort, stockExporterAdapterPort, projectUseCasesPort)
	stockUseCasesPort := ProvideSupplyStockUseCasesPort(stockUseCases)
	supplyUseCases := ProvideSupplyUseCases(supplyRepositoryPort, supplyExporterAdapterPort, stockUseCasesPort)
	supplyUseCasesPort := ProvideSupplyUseCasesPort(supplyUseCases)
	supplyConfigAPIPort := ProvideSupplyConfigAPI(config)
	supplyMiddlewaresEnginePort := ProvideSupplyMiddlewaresEnginePort(middlewares)
	supplyHandler := ProvideSupplyHandler(supplyGinEnginePort, supplyUseCasesPort, supplyConfigAPIPort, supplyMiddlewaresEnginePort)
	categoryGinEnginePort := ProvideCategoryGinEnginePort(server)
	categoryGormEnginePort := ProvideCategoryGormEnginePort(repository)
	categoryRepository := ProvideCategoryRepository(categoryGormEnginePort)
	categoryRepositoryPort := ProvideCategoryRepositoryPort(categoryRepository)
	categoryUseCases := ProvideCategoryUseCases(categoryRepositoryPort)
	categoryUseCasesPort := ProvideCategoryUseCasesPort(categoryUseCases)
	categoryConfigAPIPort := ProvideCategoryConfigAPI(config)
	categoryMiddlewaresEnginePort := ProvideCategoryMiddlewaresEnginePort(middlewares)
	categoryHandler := ProvideCategoryHandler(categoryGinEnginePort, categoryUseCasesPort, categoryConfigAPIPort, categoryMiddlewaresEnginePort)
	bparamsGinEnginePort := ProvideBusinessParametersGinEnginePort(server)
	bparamsGormEnginePort := ProvideBusinessParametersGormEnginePort(repository)
	bparamsRepository := ProvideBusinessParametersRepository(bparamsGormEnginePort)
	bparamsRepositoryPort := ProvideBusinessParametersRepositoryPort(bparamsRepository)
	bparamsUseCases := ProvideBusinessParametersUseCases(bparamsRepositoryPort)
	bparamsUseCasesPort := ProvideBusinessParametersUseCasesPort(bparamsUseCases)
	bparamsConfigAPIPort := ProvideBusinessParametersConfigAPI(config)
	bparamsMiddlewaresEnginePort := ProvideBusinessParametersMiddlewaresEnginePort(middlewares)
	bparamsHandler := ProvideBusinessParametersHandler(bparamsGinEnginePort, bparamsUseCasesPort, bparamsConfigAPIPort, bparamsMiddlewaresEnginePort)
	classtypeGinEnginePort := ProvideClassTypeGinEnginePort(server)
	classtypeGormEnginePort := ProvideClassTypeGormEnginePort(repository)
	classtypeRepository := ProvideClassTypeRepository(classtypeGormEnginePort)
	classtypeRepositoryPort := ProvideClassTypeRepositoryPort(classtypeRepository)
	classtypeUseCases := ProvideClassTypeUseCases(classtypeRepositoryPort)
	classtypeUseCasesPort := ProvideClassTypeUseCasesPort(classtypeUseCases)
	classtypeConfigAPIPort := ProvideClassTypeConfigAPI(config)
	classtypeMiddlewaresEnginePort := ProvideClassTypeMiddlewaresEnginePort(middlewares)
	classtypeHandler := ProvideClassTypeHandler(classtypeGinEnginePort, classtypeUseCasesPort, classtypeConfigAPIPort, classtypeMiddlewaresEnginePort)
	dollarGinEnginePort := ProvideDollarGinEnginePort(server)
	dollarGormEnginePort := ProvideDollarGormEnginePort(repository)
	dollarRepository := ProvideDollarRepository(dollarGormEnginePort)
	dollarRepositoryPort := ProvideDollarRepositoryPort(dollarRepository)
	dollarUseCases := ProvideDollarUseCases(dollarRepositoryPort)
	useCasePort := ProvideDollarUseCasePort(dollarUseCases)
	dollarConfigAPIPort := ProvideDollarConfigAPI(config)
	dollarMiddlewaresEnginePort := ProvideDollarMiddlewaresEnginePort(middlewares)
	dollarHandler := ProvideDollarHandler(dollarGinEnginePort, useCasePort, dollarConfigAPIPort, dollarMiddlewaresEnginePort)
	workorderGinEnginePort := ProvideWorkOrderGinEnginePort(server)
	service, err := ProvidePkgExcelService()
	if err != nil {
		return nil, err
	}
	workorderXLSXEnginePort := ProvideXLSXEnginePort(service)
	workorderExporterAdapterPort := ProvideExporterPort(workorderXLSXEnginePort)
	workorderUseCases := ProvideWorkOrderUseCases(workorderRepositoryPort, workorderExporterAdapterPort)
	workorderUseCasesPort := ProvideWorkOrderUseCasesPort(workorderUseCases)
	workorderConfigAPIPort := ProvideWorkOrderConfigAPI(config)
	workorderMiddlewaresEnginePort := ProvideWorkOrderMiddlewaresEnginePort(middlewares)
	workorderHandler := ProvideWorkOrderHandler(workorderGinEnginePort, workorderUseCasesPort, workorderConfigAPIPort, workorderMiddlewaresEnginePort)
	laborGinEnginePort := ProvideLaborGinEnginePort(server)
	laborGormEnginePort := ProvideLaborGormEnginePort(repository)
	laborRepository := ProvideLaborRepository(laborGormEnginePort)
	laborRepositoryPort := ProvideLaborRepositoryPort(laborRepository)
	laborExcelService, err := ProvideLaborPkgExcelService()
	if err != nil {
		return nil, err
	}
	laborXLSXEnginePort := ProvideLaborXLSXEnginePort(laborExcelService)
	laborExporterAdapterPort := ProvideLaborExporterPort(laborXLSXEnginePort)
	laborUseCases := ProvideLaborUseCases(laborRepositoryPort, laborExporterAdapterPort, projectUseCasesPort)
	laborUseCasesPort := ProvideLaborUseCasesPort(laborUseCases)
	laborConfigAPIPort := ProvideLaborConfigAPI(config)
	laborMiddlewaresEnginePort := ProvideLaborMiddlewaresEnginePort(middlewares)
	laborHandler := ProvideLaborHandler(laborGinEnginePort, laborUseCasesPort, laborConfigAPIPort, laborMiddlewaresEnginePort)
	invoiceGinEnginePort := ProvideInvoiceGinEnginePort(server)
	invoiceGormEnginePort := ProvideInvoiceGormEnginePort(repository)
	invoiceRepository := ProvideInvoiceRepository(invoiceGormEnginePort)
	invoiceRepositoryPort := ProvideInvoiceRepositoryPort(invoiceRepository)
	invoiceUseCases := ProvideInvoiceUseCases(invoiceRepositoryPort)
	invoiceUseCasePort := ProvideInvoiceUseCasePort(invoiceUseCases)
	invoiceConfigAPIPort := ProvideInvoiceConfigAPI(config)
	invoiceMiddlewaresEnginePort := ProvideInvoiceMiddlewaresEnginePort(middlewares)
	invoiceHandler := ProvideInvoiceHandler(invoiceGinEnginePort, invoiceUseCasePort, invoiceConfigAPIPort, invoiceMiddlewaresEnginePort)
	commercializationGinEnginePort := ProvideCommercializationGinEnginePort(server)
	commercializationGormEnginePort := ProvideCommercializationGormEnginePort(repository)
	commercializationRepository := ProvideCommercializationRepository(commercializationGormEnginePort)
	commercializationRepositoryPort := ProvideCommercializationRepositoryPort(commercializationRepository)
	commercializationUseCases := ProvideCommercializationUseCases(commercializationRepositoryPort)
	commercializationUseCasePort := ProvideCommercializationUseCasePort(commercializationUseCases)
	commercializationConfigAPIPort := ProvideCommercializationConfigAPI(config)
	commercializationMiddlewaresEnginePort := ProvideCommercializationMiddlewaresEnginePort(middlewares)
	commercializationHandler := ProvideCommercializationHandler(commercializationGinEnginePort, commercializationUseCasePort, commercializationConfigAPIPort, commercializationMiddlewaresEnginePort)
	stockGinEnginePort := ProvideStockGinEnginePort(server)
	useCasesPort2 := ProvideStockUseCasesPort(stockUseCases)
	stockConfigAPIPort := ProvideStockConfigAPI(config)
	stockMiddlewaresEnginePort := ProvideStockMiddlewaresEnginePort(middlewares)
	stockHandler := ProvideStockHandler(stockGinEnginePort, useCasesPort2, stockConfigAPIPort, stockMiddlewaresEnginePort)
	aiGinEnginePort := ProvideAIGinEnginePort(server)
	ai := ProvideConfigAI(config)
	client := ProvideAIClient(ai)
	usecasesUseCases := ProvideAIUseCases(client)
	aiUseCasesPort := ProvideAIUseCasesPort(usecasesUseCases)
	aiConfigAPIPort := ProvideAIConfigAPI(config)
	aiMiddlewaresEnginePort := ProvideAIMiddlewaresEnginePort(middlewares)
	aiHandler := ProvideAIHandler(aiGinEnginePort, aiUseCasesPort, aiConfigAPIPort, aiMiddlewaresEnginePort)
	dependencies := &Dependencies{
		Config:                    config,
		GinEngine:                 server,
		GormRepo:                  repository,
		Middlewares:               middlewares,
		WordsSuggester:            pkgsuggesterWordsSuggester,
		CustomerHandler:           handler,
		CampaignHandler:           campaignHandler,
		DashboardHandler:          dashboardHandler,
		DataIntegrityHandler:      dataintegrityHandler,
		InvestorHandler:           investorHandler,
		CropHandler:               cropHandler,
		LotHandler:                lotHandler,
		FieldHandler:              fieldHandler,
		ManagerHandler:            managerHandler,
		ProjectHandler:            projectHandler,
		ProviderHandler:           providerHandler,
		ReportHandler:             reportHandler,
		LeaseTypeHandler:          leasetypeHandler,
		SupplyHandler:             supplyHandler,
		CategoryHandler:           categoryHandler,
		BusinessParametersHandler: bparamsHandler,
		ClassTypeHandler:          classtypeHandler,
		DollarHandler:             dollarHandler,
		WorkOrderHandler:          workorderHandler,
		LaborHandler:              laborHandler,
		InvoiceHandler:            invoiceHandler,
		CommercializationHandler:  commercializationHandler,
		StockHandler:              stockHandler,
		AIHandler:                 aiHandler,
	}
	return dependencies, nil
}

// wire.go:

type Dependencies struct {
	Config                    *config.Config
	GinEngine                 *pkggin.Server
	GormRepo                  *pkggorm.Repository
	Middlewares               *pkgmwr.Middlewares
	WordsSuggester            *pkgsuggester.WordsSuggester
	CustomerHandler           *customer.Handler
	CampaignHandler           *campaign.Handler
	DashboardHandler          *dashboard.Handler
	DataIntegrityHandler      *dataintegrity.Handler
	InvestorHandler           *investor.Handler
	CropHandler               *crop.Handler
	LotHandler                *lot.Handler
	FieldHandler              *field.Handler
	ManagerHandler            *manager.Handler
	ProjectHandler            *project.Handler
	ProviderHandler           *provider.Handler
	ReportHandler             *report.ReportHandler
	LeaseTypeHandler          *leasetype.Handler
	SupplyHandler             *supply.Handler
	CategoryHandler           *category.Handler
	BusinessParametersHandler *bparams.Handler
	ClassTypeHandler          *classtype.Handler
	DollarHandler             *dollar.Handler
	WorkOrderHandler          *workorder.Handler
	LaborHandler              *labor.Handler
	InvoiceHandler            *invoice.Handler
	CommercializationHandler  *commercialization.Handler
	StockHandler              *stock.Handler
	AIHandler                 *ai.Handler
}
