// Code generated by MockGen. DO NOT EDIT.
// Source: usecases.go

// Package dataintegrity is a generated GoMock package.
package dataintegrity

import (
	context "context"
	reflect "reflect"

	dashboardDomain "github.com/devpablocristo/ponti-backend/internal/dashboard/usecases/domain"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockDashboardRepositoryPort is a mock of DashboardRepositoryPort interface.
type MockDashboardRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardRepositoryPortMockRecorder
}

// MockDashboardRepositoryPortMockRecorder is the mock recorder for MockDashboardRepositoryPort.
type MockDashboardRepositoryPortMockRecorder struct {
	mock *MockDashboardRepositoryPort
}

// NewMockDashboardRepositoryPort creates a new mock instance.
func NewMockDashboardRepositoryPort(ctrl *gomock.Controller) *MockDashboardRepositoryPort {
	mock := &MockDashboardRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockDashboardRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardRepositoryPort) EXPECT() *MockDashboardRepositoryPortMockRecorder {
	return m.recorder
}

// GetDashboard mocks base method.
func (m *MockDashboardRepositoryPort) GetDashboard(ctx context.Context, filter dashboardDomain.DashboardFilter) (*dashboardDomain.DashboardData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboard", ctx, filter)
	ret0, _ := ret[0].(*dashboardDomain.DashboardData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboard indicates an expected call of GetDashboard.
func (mr *MockDashboardRepositoryPortMockRecorder) GetDashboard(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboard", reflect.TypeOf((*MockDashboardRepositoryPort)(nil).GetDashboard), ctx, filter)
}

// MockWorkOrderRepositoryPort is a mock of WorkOrderRepositoryPort interface.
type MockWorkOrderRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockWorkOrderRepositoryPortMockRecorder
}

// MockWorkOrderRepositoryPortMockRecorder is the mock recorder for MockWorkOrderRepositoryPort.
type MockWorkOrderRepositoryPortMockRecorder struct {
	mock *MockWorkOrderRepositoryPort
}

// NewMockWorkOrderRepositoryPort creates a new mock instance.
func NewMockWorkOrderRepositoryPort(ctrl *gomock.Controller) *MockWorkOrderRepositoryPort {
	mock := &MockWorkOrderRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockWorkOrderRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkOrderRepositoryPort) EXPECT() *MockWorkOrderRepositoryPortMockRecorder {
	return m.recorder
}

// GetRawDirectCost mocks base method.
func (m *MockWorkOrderRepositoryPort) GetRawDirectCost(ctx context.Context, projectID int64) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawDirectCost", ctx, projectID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRawDirectCost indicates an expected call of GetRawDirectCost.
func (mr *MockWorkOrderRepositoryPortMockRecorder) GetRawDirectCost(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawDirectCost", reflect.TypeOf((*MockWorkOrderRepositoryPort)(nil).GetRawDirectCost), ctx, projectID)
}

// MockReportRepositoryPort is a mock of ReportRepositoryPort interface.
type MockReportRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryPortMockRecorder
}

// MockReportRepositoryPortMockRecorder is the mock recorder for MockReportRepositoryPort.
type MockReportRepositoryPortMockRecorder struct {
	mock *MockReportRepositoryPort
}

// NewMockReportRepositoryPort creates a new mock instance.
func NewMockReportRepositoryPort(ctrl *gomock.Controller) *MockReportRepositoryPort {
	mock := &MockReportRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepositoryPort) EXPECT() *MockReportRepositoryPortMockRecorder {
	return m.recorder
}

// GetRawNetIncome mocks base method.
func (m *MockReportRepositoryPort) GetRawNetIncome(ctx context.Context, projectID int64) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawNetIncome", ctx, projectID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRawNetIncome indicates an expected call of GetRawNetIncome.
func (mr *MockReportRepositoryPortMockRecorder) GetRawNetIncome(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawNetIncome", reflect.TypeOf((*MockReportRepositoryPort)(nil).GetRawNetIncome), ctx, projectID)
}

// MockSupplyRepositoryPort is a mock of SupplyRepositoryPort interface.
type MockSupplyRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockSupplyRepositoryPortMockRecorder
}

// MockSupplyRepositoryPortMockRecorder is the mock recorder for MockSupplyRepositoryPort.
type MockSupplyRepositoryPortMockRecorder struct {
	mock *MockSupplyRepositoryPort
}

// NewMockSupplyRepositoryPort creates a new mock instance.
func NewMockSupplyRepositoryPort(ctrl *gomock.Controller) *MockSupplyRepositoryPort {
	mock := &MockSupplyRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockSupplyRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupplyRepositoryPort) EXPECT() *MockSupplyRepositoryPortMockRecorder {
	return m.recorder
}

// GetRawSupplyInvestment mocks base method.
func (m *MockSupplyRepositoryPort) GetRawSupplyInvestment(ctx context.Context, projectID int64) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawSupplyInvestment", ctx, projectID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRawSupplyInvestment indicates an expected call of GetRawSupplyInvestment.
func (mr *MockSupplyRepositoryPortMockRecorder) GetRawSupplyInvestment(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawSupplyInvestment", reflect.TypeOf((*MockSupplyRepositoryPort)(nil).GetRawSupplyInvestment), ctx, projectID)
}

// MockProjectRepositoryPort is a mock of ProjectRepositoryPort interface.
type MockProjectRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryPortMockRecorder
}

// MockProjectRepositoryPortMockRecorder is the mock recorder for MockProjectRepositoryPort.
type MockProjectRepositoryPortMockRecorder struct {
	mock *MockProjectRepositoryPort
}

// NewMockProjectRepositoryPort creates a new mock instance.
func NewMockProjectRepositoryPort(ctrl *gomock.Controller) *MockProjectRepositoryPort {
	mock := &MockProjectRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepositoryPort) EXPECT() *MockProjectRepositoryPortMockRecorder {
	return m.recorder
}

// GetRawAdminCostTotal mocks base method.
func (m *MockProjectRepositoryPort) GetRawAdminCostTotal(ctx context.Context, projectID int64) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawAdminCostTotal", ctx, projectID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRawAdminCostTotal indicates an expected call of GetRawAdminCostTotal.
func (mr *MockProjectRepositoryPortMockRecorder) GetRawAdminCostTotal(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawAdminCostTotal", reflect.TypeOf((*MockProjectRepositoryPort)(nil).GetRawAdminCostTotal), ctx, projectID)
}

// MockLotRepositoryPort is a mock of LotRepositoryPort interface.
type MockLotRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockLotRepositoryPortMockRecorder
}

// MockLotRepositoryPortMockRecorder is the mock recorder for MockLotRepositoryPort.
type MockLotRepositoryPortMockRecorder struct {
	mock *MockLotRepositoryPort
}

// NewMockLotRepositoryPort creates a new mock instance.
func NewMockLotRepositoryPort(ctrl *gomock.Controller) *MockLotRepositoryPort {
	mock := &MockLotRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockLotRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLotRepositoryPort) EXPECT() *MockLotRepositoryPortMockRecorder {
	return m.recorder
}

// GetRawLeaseExecuted mocks base method.
func (m *MockLotRepositoryPort) GetRawLeaseExecuted(ctx context.Context, projectID int64) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRawLeaseExecuted", ctx, projectID)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRawLeaseExecuted indicates an expected call of GetRawLeaseExecuted.
func (mr *MockLotRepositoryPortMockRecorder) GetRawLeaseExecuted(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRawLeaseExecuted", reflect.TypeOf((*MockLotRepositoryPort)(nil).GetRawLeaseExecuted), ctx, projectID)
}
